"use client";
import { useState } from "react";
const questions = [
  { q: "C প্রোগ্রামের প্রধান ফাংশনের নাম কী?", options: ["main()","start()","begin()","run()"], answer: 0, explanation: "C প্রোগ্রাম সবসময় main() ফাংশন থেকে শুরু হয়। এটি বাধ্যতামূলক এবং int main() বা void main() আকারে লেখা হয়।" },
  { q: "C ভাষায় পূর্ণসংখ্যা (Integer) ধরনের ডেটা টাইপ কোনটি?", options: ["string","float","int","char"], answer: 2, explanation: "int = Integer (পূর্ণসংখ্যা)। যেমন: int age = 17;। float = দশমিক, char = একটি অক্ষর।" },
  { q: "#include <stdio.h> লাইনটির কাজ কী?", options: ["প্রোগ্রাম শুরু করা","Standard Input/Output লাইব্রেরি অন্তর্ভুক্ত করা","ভেরিয়েবল ঘোষণা করা","লুপ শুরু করা"], answer: 1, explanation: "#include <stdio.h> — stdio.h হেডার ফাইল অন্তর্ভুক্ত করে। এতে printf(), scanf() ইত্যাদি ফাংশন থাকে।" },
  { q: "C-তে স্ক্রিনে আউটপুট দিতে কোন ফাংশন ব্যবহার হয়?", options: ["print()","cout","write()","printf()"], answer: 3, explanation: "printf() — Formatted Print। উদাহরণ: printf(\"বয়স: %d\", age); C-তে আউটপুটের প্রধান ফাংশন।" },
  { q: "C-তে ব্যবহারকারীর কাছ থেকে ইনপুট নিতে কোন ফাংশন ব্যবহার হয়?", options: ["input()","cin","scanf()","read()"], answer: 2, explanation: "scanf() — Formatted Scan। উদাহরণ: scanf(\"%d\", &num); — &num মানে num ভেরিয়েবলের ঠিকানা।" },
  { q: "C ভাষায় for লুপের সঠিক গঠন কোনটি?", options: ["for(init; condition; update)","for(condition)","for(init, condition)","loop(init; condition)"], answer: 0, explanation: "for লুপের গঠন: for(initialization; condition; update) { body }। যেমন: for(i=1; i<=10; i++) { printf(\"%d\",i); }" },
  { q: "C-তে char ডেটা টাইপের আকার কত বাইট?", options: ["২ বাইট","৪ বাইট","৮ বাইট","১ বাইট"], answer: 3, explanation: "char = 1 byte (8 bits)। একটি একক অক্ষর সংরক্ষণ করে। যেমন: char grade = 'A';" },
  { q: "C প্রোগ্রামে একটি ব্লক (block) কোন চিহ্ন দিয়ে ঘেরা থাকে?", options: ["( ) (Parentheses)","{ } (Curly braces)","[ ] (Square brackets)","< > (Angle brackets)"], answer: 1, explanation: "{ } (Curly braces) দিয়ে C-তে একটি কোড ব্লক ঘেরা হয়। যেমন: main() { ... } বা if(x>0) { ... }।" },
  { q: "নিচের কোন C কোডটি 1 থেকে 5 পর্যন্ত সংখ্যা প্রিন্ট করবে?", options: ["for(i=1;i<=5;i++) printf(\"%d\",i);","for(i=0;i<5;i++) printf(\"%d\",i);","for(i=1;i<5;i++) printf(\"%d\",i);","while(i<=5) printf(\"%d\",i);"], answer: 0, explanation: "for(i=1; i<=5; i++) — i শুরু 1 থেকে, শর্ত i<=5 (1,2,3,4,5 পর্যন্ত), প্রতিবার 1 বাড়ে। ফলে 1 2 3 4 5 প্রিন্ট হবে।" },
  { q: "C ভাষায় ফাংশন থেকে মান ফেরত দিতে কোন কীওয়ার্ড ব্যবহার হয়?", options: ["send","output","give","return"], answer: 3, explanation: "return কীওয়ার্ড ফাংশন থেকে মান ফেরত পাঠায়। যেমন: int add(int a, int b) { return a + b; }" },
];
export default function CProgrammingQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#16a34a";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — C প্রোগ্রামিং</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f0fdf4",border:"1px solid #bbf7d0",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500,fontFamily:"system-ui,monospace"}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
