"use client";
import { useState } from "react";
const C = "#dc2626";
const questions = [
  { q: "ডিকোডার (Decoder) কী করে?", options: ["n ইনপুট থেকে 2ⁿ আউটপুট তৈরি করে", "2ⁿ ইনপুট থেকে n আউটপুট তৈরি করে", "বাইনারি যোগ করে", "কোড রূপান্তর করে"], answer: 0, explanation: "ডিকোডার n ইনপুট নিয়ে সর্বোচ্চ 2ⁿ আউটপুট দেয়। যেমন 2-to-4 ডিকোডারে 2 ইনপুট ও 4 আউটপুট।" },
  { q: "এনকোডার (Encoder) কী করে?", options: ["n ইনপুট থেকে 2ⁿ আউটপুট তৈরি করে", "লজিক গেট সরলীকরণ করে", "2ⁿ ইনপুট থেকে n আউটপুট তৈরি করে", "ডিকোডারের বিপরীত কাজ নয়"], answer: 2, explanation: "এনকোডার ডিকোডারের বিপরীত: 2ⁿ ইনপুট নিয়ে n বিট আউটপুট দেয়।" },
  { q: "2-to-4 ডিকোডারে A=0, B=1 হলে কোন আউটপুট লাইন সক্রিয়?", options: ["D0", "D1", "D2", "D3"], answer: 1, explanation: "AB=01 (দশমিকে 1) তাই D1 সক্রিয়। D0=00, D1=01, D2=10, D3=11।" },
  { q: "2-to-4 ডিকোডারে A=1, B=1 হলে কোন আউটপুট সক্রিয়?", options: ["D0", "D1", "D2", "D3"], answer: 3, explanation: "AB=11 (দশমিকে 3) তাই D3 সক্রিয়।" },
  { q: "৭-সেগমেন্ট ডিসপ্লেতে কয়টি সেগমেন্ট থাকে?", options: ["8টি", "4টি", "7টি", "16টি"], answer: 2, explanation: "৭-সেগমেন্ট ডিসপ্লেতে a,b,c,d,e,f,g — মোট ৭টি সেগমেন্ট থাকে।" },
  { q: "BCD to 7-Segment ডিকোডার কোথায় ব্যবহার হয়?", options: ["ডিজিটাল ডিসপ্লেতে", "মেমোরিতে", "RAM-এ", "CPU-তে"], answer: 0, explanation: "BCD to 7-Segment ডিকোডার ডিজিটাল ঘড়ি, ক্যালকুলেটর, মিটারে সংখ্যা দেখাতে ব্যবহার হয়।" },
  { q: "4-to-2 এনকোডারে D2=1 (বাকি 0) হলে আউটপুট B1B0 কত?", options: ["01", "11", "00", "10"], answer: 3, explanation: "D2 মানে দশমিক 2 = বাইনারি 10। তাই B1=1, B0=0 → আউটপুট 10।" },
  { q: "Enable (EN) পিন ডিকোডারে কী কাজ করে?", options: ["ইনপুট বাড়ায়", "সার্কিট সক্রিয় বা নিষ্ক্রিয় করে", "আউটপুট উল্টায়", "Carry তৈরি করে"], answer: 1, explanation: "Enable পিন 1 হলে ডিকোডার কাজ করে, 0 হলে সব আউটপুট 0 হয়।" },
  { q: "3-to-8 ডিকোডারে সর্বোচ্চ কয়টি আউটপুট লাইন থাকে?", options: ["8টি", "3টি", "6টি", "16টি"], answer: 0, explanation: "n=3 হলে 2³=8টি আউটপুট লাইন।" },
  { q: "Priority Encoder কী?", options: ["শুধুমাত্র একটি ইনপুট নেয়", "BCD কোড তৈরি করে", "ডিকোডারের মতো কাজ করে", "একাধিক ইনপুট সক্রিয় থাকলে সর্বোচ্চ অগ্রাধিকারের ইনপুট এনকোড করে"], answer: 3, explanation: "Priority Encoder একাধিক ইনপুট সক্রিয় থাকলে সর্বোচ্চ priority-র ইনপুট এনকোড করে।" },
];
export default function EncoderDecoderQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const S=(bg:string):React.CSSProperties=>({background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"});
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — এনকোডার ও ডিকোডার</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score}/১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return <div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}<div style={{fontSize:"0.78rem",color:"#64748b",marginTop:"0.2rem"}}>{qq.explanation}</div></div></div>;})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#fef2f2",border:"1px solid #fecaca",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})}</div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
