"use client";
import { useState } from "react";
const questions = [
  { q: "SQL-এর পূর্ণরূপ কী?", options: ["Structured Query Language","Simple Query Language","Sequential Query Language","Standard Query Language"], answer: 0, explanation: "SQL = Structured Query Language। রিলেশনাল ডেটাবেজ তৈরি ও পরিচালনার জন্য আন্তর্জাতিকভাবে স্বীকৃত ভাষা।" },
  { q: "ডেটাবেজ টেবিলে প্রতিটি Record-কে অদ্বিতীয়ভাবে চিহ্নিত করার Field-কে কী বলে?", options: ["Foreign Key","Candidate Key","Primary Key","Composite Key"], answer: 2, explanation: "Primary Key একটি Field (বা Fields-এর সমষ্টি) যা প্রতিটি Record-কে অদ্বিতীয়ভাবে চিহ্নিত করে। Null বা Duplicate হতে পারে না।" },
  { q: "Foreign Key কী?", options: ["নিজ টেবিলের Primary Key","অন্য টেবিলের Primary Key-র রেফারেন্স","কোনো বিশেষ Key নয়","Duplicate মান রাখার Field"], answer: 1, explanation: "Foreign Key হলো একটি টেবিলের Field যা অন্য টেবিলের Primary Key-কে রেফার করে — টেবিলগুলোর মধ্যে সম্পর্ক তৈরি করে।" },
  { q: "SQL-এ টেবিল থেকে ডেটা বের করার কমান্ড কোনটি?", options: ["INSERT","UPDATE","DELETE","SELECT"], answer: 3, explanation: "SELECT কমান্ড টেবিল থেকে ডেটা বের করে। মূল গঠন: SELECT column FROM table WHERE condition;" },
  { q: "SQL-এ নতুন টেবিল তৈরির কমান্ড কোনটি?", options: ["MAKE TABLE","NEW TABLE","CREATE TABLE","BUILD TABLE"], answer: 2, explanation: "CREATE TABLE কমান্ড দিয়ে নতুন টেবিল তৈরি করা হয়। যেমন: CREATE TABLE Student (ID int, Name varchar(50));" },
  { q: "SQL-এ টেবিলে নতুন ডেটা যোগ করার কমান্ড কোনটি?", options: ["INSERT INTO","ADD INTO","PUT INTO","APPEND INTO"], answer: 0, explanation: "INSERT INTO কমান্ড দিয়ে টেবিলে নতুন Record যোগ করা হয়। গঠন: INSERT INTO Table VALUES (মান১, মান২, ...);" },
  { q: "SQL-এ বিদ্যমান ডেটা পরিবর্তন করার কমান্ড কোনটি?", options: ["MODIFY","CHANGE","EDIT","UPDATE"], answer: 3, explanation: "UPDATE কমান্ড দিয়ে টেবিলের বিদ্যমান ডেটা পরিবর্তন করা হয়। গঠন: UPDATE Table SET column=মান WHERE condition;" },
  { q: "SQL-এ টেবিল থেকে ডেটা মুছে ফেলার কমান্ড কোনটি?", options: ["REMOVE","DELETE","DROP","CLEAR"], answer: 1, explanation: "DELETE FROM Table WHERE condition — নির্দিষ্ট শর্তে Record মুছে ফেলে। DROP TABLE সম্পূর্ণ টেবিল মুছে দেয়।" },
  { q: "SELECT * FROM Student WHERE Class='XI'; — এই SQL কমান্ড কী করবে?", options: ["Student টেবিল থেকে Class='XI' সব ছাত্রের সব কলাম দেখাবে","সব ছাত্রের নাম মুছবে","XI ক্লাস তৈরি করবে","Student টেবিল মুছবে"], answer: 0, explanation: "SELECT * = সব কলাম, FROM Student = Student টেবিল থেকে, WHERE Class='XI' = শুধু Class XI-র রেকর্ড। ফলাফল: XI শ্রেণির সব ছাত্রের তথ্য।" },
  { q: "DDL ও DML-এর পার্থক্য কী?", options: ["DML কাঠামো তৈরি করে, DDL ডেটা পরিচালনা করে","দুটি একই","DDL শুধু মুছে ফেলে","DDL কাঠামো তৈরি করে (CREATE/DROP), DML ডেটা পরিচালনা করে (SELECT/INSERT)"], answer: 3, explanation: "DDL (Data Definition Language): CREATE, DROP, ALTER — টেবিলের কাঠামো। DML (Data Manipulation Language): SELECT, INSERT, UPDATE, DELETE — ডেটা পরিচালনা।" },
];
export default function SQLQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#16a34a";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — SQL ও রিলেশনাল ডেটাবেজ</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f0fdf4",border:"1px solid #bbf7d0",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500,fontFamily:"system-ui,monospace"}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
