"use client";
import { useState } from "react";
const questions = [
  { q: "বর্তমানে সবচেয়ে জনপ্রিয় ডেটাবেজ মডেল কোনটি?", options: ["রিলেশনাল মডেল (Relational Model)","হায়ারার্কিক্যাল মডেল","নেটওয়ার্ক মডেল","অবজেক্ট মডেল"], answer: 0, explanation: "Relational Model সবচেয়ে জনপ্রিয় — ডেটা টেবিলে রাখা হয়, SQL দিয়ে পরিচালনা করা যায়। MySQL, Oracle এই মডেল ব্যবহার করে।" },
  { q: "হায়ারার্কিক্যাল ডেটাবেজ মডেলের কাঠামো কেমন?", options: ["জালের মতো","টেবিলের মতো","গাছের মতো, Parent-Child সম্পর্ক","বৃত্তাকার"], answer: 2, explanation: "Hierarchical Model গাছের মতো — একটি Root Node এবং তার নিচে Child Node। প্রতিটি Child-এর মাত্র একটি Parent থাকে।" },
  { q: "Entity কী?", options: ["ডেটাবেজ সফটওয়্যার","বাস্তব জগতের বস্তু যার সম্পর্কে ডেটা রাখা হয়","টেবিলের একটি কলাম","ডেটার প্রকার"], answer: 1, explanation: "Entity হলো বাস্তব জগতের এমন বস্তু বা ধারণা যার সম্পর্কে ডেটা সংরক্ষণ করা হয়। যেমন: ছাত্র, শিক্ষক, বই।" },
  { q: "Attribute কী?", options: ["Entity-র নাম","ডেটাবেজের টেবিল","দুটি Entity-র সম্পর্ক","Entity-র বৈশিষ্ট্য"], answer: 3, explanation: "Attribute হলো Entity-র বৈশিষ্ট্য। যেমন: ছাত্র Entity-র Attribute হলো নাম, রোল নম্বর, বয়স, শ্রেণি।" },
  { q: "নেটওয়ার্ক মডেল ও হায়ারার্কিক্যাল মডেলের পার্থক্য কী?", options: ["হায়ারার্কিক্যালে একাধিক Parent থাকে","নেটওয়ার্ক মডেল টেবিল ব্যবহার করে","নেটওয়ার্কে একটি Child-এর একাধিক Parent থাকতে পারে","কোনো পার্থক্য নেই"], answer: 2, explanation: "Network Model-এ একটি Child Node-এর একাধিক Parent থাকতে পারে — জালের মতো কাঠামো। Hierarchical-এ প্রতিটি Child-এর মাত্র একটি Parent।" },
  { q: "E-R Diagram-এর পূর্ণরূপ কী?", options: ["Entity-Relationship Diagram","Electronic-Record Diagram","Entity-Relational Data","Extended-Record Diagram"], answer: 0, explanation: "E-R Diagram = Entity-Relationship Diagram। ডেটাবেজের কাঠামো চিত্রের আকারে দেখানোর পদ্ধতি।" },
  { q: "Relationship-এর '1:N' বলতে কী বোঝায়?", options: ["একটির সাথে একটির সম্পর্ক","অনেকের সাথে অনেকের সম্পর্ক","কোনো সম্পর্ক নেই","একটি Entity-র সাথে অনেক Entity-র সম্পর্ক"], answer: 3, explanation: "1:N (One-to-Many) মানে একটি Entity-র সাথে অনেক Entity-র সম্পর্ক। যেমন: একজন শিক্ষক অনেক ছাত্রকে পড়ান।" },
  { q: "রিলেশনাল মডেলে ডেটা কীভাবে সংরক্ষিত থাকে?", options: ["গাছের কাঠামোতে","দ্বিমাত্রিক টেবিলে (Row ও Column)","জালের কাঠামোতে","শুধু একটি লিস্টে"], answer: 1, explanation: "Relational Model-এ ডেটা দ্বিমাত্রিক টেবিলে থাকে — Row (Record) ও Column (Field)। একাধিক টেবিল Key দিয়ে সংযুক্ত।" },
  { q: "M:N (Many-to-Many) Relationship-এর উদাহরণ কোনটি?", options: ["ছাত্র ও বিষয় — একজন ছাত্র অনেক বিষয় পড়ে, একটি বিষয়ে অনেক ছাত্র","শিক্ষক ও শ্রেণি","বই ও লেখক","ছাত্র ও রোল নম্বর"], answer: 0, explanation: "M:N: ছাত্র-বিষয় — একজন ছাত্র একাধিক বিষয় পড়ে এবং একটি বিষয় একাধিক ছাত্র পড়ে।" },
  { q: "হায়ারার্কিক্যাল মডেলের প্রধান অসুবিধা কোনটি?", options: ["দ্রুত ডেটা খোঁজে না পাওয়া","টেবিল তৈরি করা যায় না","SQL সাপোর্ট করে না","M:N সম্পর্ক প্রকাশ করা যায় না"], answer: 3, explanation: "Hierarchical Model-এ Many-to-Many (M:N) সম্পর্ক প্রকাশ করা যায় না এবং গাছের কাঠামোর বাইরে ডেটা সংযুক্ত করা কঠিন।" },
];
export default function DatabaseModelsQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#7c3aed";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — ডেটাবেজ মডেল</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f5f3ff",border:"1px solid #ddd6fe",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
