"use client";
import { useState } from "react";
const questions = [
  { q: "JavaScript-এ ভেরিয়েবল ঘোষণায় কোনটি ব্যবহার করা হয়?", options: ["var, let, const","variable, define, set","dim, int, string","declare, assign, value"], answer: 0, explanation: "JavaScript-এ var (পুরনো), let (block-scoped), const (পরিবর্তন হয় না) — তিনটি কীওয়ার্ড দিয়ে ভেরিয়েবল ঘোষণা করা হয়।" },
  { q: "JavaScript-এ String ডেটা টাইপ কীভাবে লেখা হয়?", options: ["নাম — কোনো চিহ্ন ছাড়া","[নাম] — বর্গ বন্ধনীতে","'নাম' বা \"নাম\" — উদ্ধৃতিচিহ্নে","{নাম} — কোঁকড়া বন্ধনীতে"], answer: 2, explanation: "JavaScript-এ String সবসময় single quote ('') বা double quote (\"\") এর মধ্যে লেখা হয়।" },
  { q: "JavaScript-এ ফাংশন তৈরির সঠিক উপায় কোনটি?", options: ["def greet(): return 'হ্যালো'","function greet() { return 'হ্যালো'; }","func greet() { return 'হ্যালো'; }","method greet() { return 'হ্যালো'; }"], answer: 1, explanation: "JavaScript-এ function কীওয়ার্ড দিয়ে ফাংশন তৈরি হয়: function name() { ... }।" },
  { q: "HTML-এ JavaScript কোড কোন ট্যাগে লেখা হয়?", options: ["<javascript>","<js>","<code>","<script>"], answer: 3, explanation: "<script> ট্যাগের মধ্যে JavaScript কোড লেখা হয়। সাধারণত <body> শেষে অথবা <head>-এ রাখা হয়।" },
  { q: "JavaScript-এ document.getElementById() কী করে?", options: ["নতুন উপাদান তৈরি করে","উপাদান মুছে দেয়","নির্দিষ্ট ID-র HTML উপাদান খুঁজে বের করে","CSS প্রয়োগ করে"], answer: 2, explanation: "document.getElementById('myId') DOM থেকে নির্দিষ্ট ID-র HTML উপাদান খুঁজে বের করে এবং জাভাস্ক্রিপ্টে ব্যবহারের সুযোগ দেয়।" },
  { q: "JavaScript-এ onclick event কখন ঘটে?", options: ["ব্যবহারকারী কোনো উপাদানে ক্লিক করলে","পেজ লোড হলে","মাউস সরালে","কীবোর্ড চাপলে"], answer: 0, explanation: "onclick ঘটে যখন ব্যবহারকারী কোনো HTML উপাদানে (বোতাম, লিংক ইত্যাদি) ক্লিক করে।" },
  { q: "JavaScript-এ শর্তমূলক (conditional) স্টেটমেন্ট কোনটি?", options: ["when...then","case...of","check...do","if...else"], answer: 3, explanation: "JavaScript-এ if...else শর্তমূলক কাজের জন্য ব্যবহার হয়। if(condition) { ... } else { ... }।" },
  { q: "const x = 10; লেখার পর x = 20; করলে কী হবে?", options: ["x = 20 হবে","Error হবে","x = 30 হবে","কিছু হবে না"], answer: 1, explanation: "const দিয়ে ঘোষিত ভেরিয়েবল পরিবর্তন করা যায় না। পুনরায় মান দিলে TypeError হয়।" },
  { q: "JavaScript-এ array কীভাবে তৈরি হয়?", options: ["let fruits = ['আম', 'কলা', 'জাম'];","let fruits = ('আম', 'কলা', 'জাম');","let fruits = {'আম', 'কলা', 'জাম'};","array fruits = ['আম', 'কলা', 'জাম'];"], answer: 0, explanation: "JavaScript-এ array [] বর্গ বন্ধনীতে তৈরি হয়। fruits[0] = 'আম', fruits[1] = 'কলা'।" },
  { q: "DOM-এর পূর্ণরূপ কী?", options: ["Data Object Management","Document Oriented Markup","Dynamic Object Model","Document Object Model"], answer: 3, explanation: "DOM = Document Object Model। HTML ডকুমেন্টের একটি গাছের মতো উপস্থাপনা যা JavaScript দিয়ে পরিবর্তন করা যায়।" },
];
export default function JavaScriptQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#ca8a04";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — JavaScript</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#fefce8",border:"1px solid #fef08a",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500,fontFamily:"system-ui,monospace"}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
