"use client";
import { useState } from "react";
const questions = [
  { q: "অ্যালগরিদমের বৈশিষ্ট্য কোনটি নয়?", options: ["Ambiguity (অস্পষ্টতা)","Finiteness (সীমাবদ্ধতা)","Definiteness (সুনির্দিষ্টতা)","Effectiveness (কার্যকারিতা)"], answer: 0, explanation: "Ambiguity (অস্পষ্টতা) অ্যালগরিদমের বৈশিষ্ট্য নয়, বরং দোষ। অ্যালগরিদম সবসময় Definite (স্পষ্ট), Finite (শেষ হয়), Effective (কার্যকর) হতে হয়।" },
  { q: "ফ্লোচার্টে Decision (সিদ্ধান্ত) বোঝাতে কোন আকৃতি ব্যবহার হয়?", options: ["আয়তক্ষেত্র (Rectangle)","ডিম্বাকার (Oval)","হীরা (Diamond)","সমান্তরালবাহু (Parallelogram)"], answer: 2, explanation: "ফ্লোচার্টে হীরা (◇) আকৃতি Decision বোঝায়। এতে সাধারণত Yes/No বা True/False প্রশ্ন থাকে।" },
  { q: "ফ্লোচার্টে Start ও End বোঝাতে কোন আকৃতি ব্যবহার হয়?", options: ["আয়তক্ষেত্র","ডিম্বাকার বা গোলাকার (Oval/Terminal)","হীরা","তীর চিহ্ন"], answer: 1, explanation: "ফ্লোচার্টে শুরু (Start) ও শেষ (End) বোঝাতে ডিম্বাকার বা গোলাকার চিহ্ন (Terminal) ব্যবহার হয়।" },
  { q: "ফ্লোচার্টে Process (প্রক্রিয়া) বোঝাতে কোন আকৃতি ব্যবহার হয়?", options: ["হীরা","ডিম্বাকার","বৃত্ত","আয়তক্ষেত্র (Rectangle)"], answer: 3, explanation: "আয়তক্ষেত্র (□) Process বোঝায় — যেকোনো গণনা বা কার্যক্রম যেমন: sum = a + b।" },
  { q: "Input ও Output বোঝাতে ফ্লোচার্টে কোন আকৃতি ব্যবহার হয়?", options: ["আয়তক্ষেত্র","হীরা","সমান্তরালবাহু চতুর্ভুজ (Parallelogram)","ডিম্বাকার"], answer: 2, explanation: "সমান্তরালবাহু চতুর্ভুজ (▱) Input/Output বোঝায়। যেমন: 'n এর মান নাও' বা 'ফলাফল দেখাও'।" },
  { q: "সিউডোকোড কী?", options: ["প্রাকৃতিক ভাষায় প্রোগ্রামের খসড়া কোড","মেশিন ভাষায় লেখা কোড","C ভাষায় লেখা কোড","ফ্লোচার্টের বিকল্প নাম"], answer: 0, explanation: "Pseudocode হলো মানব-পাঠযোগ্য ভাষায় (ইংরেজি বা বাংলামিশ্রিত) লেখা প্রোগ্রামের খসড়া — কোনো নির্দিষ্ট ভাষার Syntax মানা হয় না।" },
  { q: "নিয়ন্ত্রণ কাঠামো কত ধরনের?", options: ["২ ধরনের","৪ ধরনের","৫ ধরনের","৩ ধরনের"], answer: 3, explanation: "তিন ধরনের নিয়ন্ত্রণ কাঠামো: ১. Sequence (ধারাবাহিক), ২. Selection (if-else), ৩. Iteration/Loop (পুনরাবৃত্তি)।" },
  { q: "১ থেকে ১০০ পর্যন্ত সংখ্যার সমষ্টি বের করার অ্যালগরিদমে কোন কাঠামো ব্যবহার হবে?", options: ["Sequence","Iteration (Loop)","Selection","Recursion"], answer: 1, explanation: "পুনরাবৃত্তিমূলক কাজে Iteration (Loop) কাঠামো ব্যবহার হয়। এখানে sum=sum+i এবং i=1 থেকে 100 পর্যন্ত বাড়ানো হবে।" },
  { q: "অ্যালগরিদমের 'Finiteness' বৈশিষ্ট্যের অর্থ কী?", options: ["অ্যালগরিদম নির্দিষ্ট সংখ্যক ধাপে শেষ হবে","অ্যালগরিদম চিরকাল চলবে","অ্যালগরিদমে Input থাকবে","অ্যালগরিদম দ্রুত হবে"], answer: 0, explanation: "Finiteness মানে অ্যালগরিদম অবশ্যই নির্দিষ্ট সংখ্যক ধাপের পর শেষ হবে — কখনো অসীম চলবে না।" },
  { q: "ফ্লোচার্টে তীর চিহ্ন (Arrow) কী বোঝায়?", options: ["Decision","প্রক্রিয়া শেষ","Input গ্রহণ","প্রোগ্রামের প্রবাহের দিক (Flow of Control)"], answer: 3, explanation: "ফ্লোচার্টে তীর চিহ্ন (Arrow) প্রোগ্রামের নিয়ন্ত্রণের প্রবাহ বোঝায় — কোন ধাপ থেকে কোন ধাপে যাবে।" },
];
export default function ProgramDesignQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#0891b2";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — প্রোগ্রাম ডিজাইন টুলস</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#ecfeff",border:"1px solid #a5f3fc",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
