"use client";
import { useState } from "react";
const questions = [
  { q: "কোনটি Guided (তারযুক্ত) মাধ্যম?", options: ["Fiber Optic Cable","Radio Wave","Microwave","Bluetooth"], answer: 0, explanation: "Guided মাধ্যম: Twisted Pair, Coaxial Cable, Fiber Optic Cable — ডেটা তারের মধ্য দিয়ে যায়। Unguided মাধ্যম: Radio, Microwave, Bluetooth — বাতাসে ছড়িয়ে পড়ে।" },
  { q: "Fiber Optic Cable ডেটা কীভাবে প্রেরণ করে?", options: ["বৈদ্যুতিক সংকেতে","রেডিও তরঙ্গে","আলোক তরঙ্গের মাধ্যমে","Microwave-এ"], answer: 2, explanation: "Fiber Optic Cable আলোক তরঙ্গ (Light Pulse) ব্যবহার করে ডেটা পাঠায়। এটি সবচেয়ে দ্রুত, নিরাপদ এবং দূরত্বে সংকেত দুর্বল হয় না।" },
  { q: "Twisted Pair ক্যাবলের সুবিধা কোনটি?", options: ["সবচেয়ে দ্রুত","সবচেয়ে সস্তা ও সহজলভ্য","সবচেয়ে নিরাপদ","সবচেয়ে দীর্ঘ দূরত্বে কার্যকর"], answer: 1, explanation: "Twisted Pair সবচেয়ে সস্তা ও সহজলভ্য মাধ্যম। LAN-এ ব্যাপকভাবে ব্যবহৃত হয়। দুটি তার পাকানো থাকায় interference কম হয়।" },
  { q: "Coaxial Cable সাধারণত কোথায় ব্যবহৃত হয়?", options: ["Wi-Fi নেটওয়ার্কে","Bluetooth সংযোগে","Satellite যোগাযোগে","Cable TV ও পুরনো Ethernet নেটওয়ার্কে"], answer: 3, explanation: "Coaxial Cable Cable TV, পুরনো Ethernet (10BASE2, 10BASE5) এবং CCTV ক্যামেরায় ব্যবহৃত হয়। একটি কেন্দ্রীয় তার Metallic Shield দ্বারা ঘেরা।" },
  { q: "Satellite যোগাযোগ কোন ধরনের মাধ্যম?", options: ["Guided (তারযুক্ত)","Hybrid","Unguided (তারবিহীন)","Optical"], answer: 2, explanation: "Satellite যোগাযোগ Unguided মাধ্যম — কোনো তার লাগে না। মহাকাশে Satellite থেকে Microwave সংকেত পৃথিবীতে আসে।" },
  { q: "Wi-Fi কোন ধরনের তরঙ্গ ব্যবহার করে?", options: ["Radio Wave","Microwave","Infrared","Fiber Optic"], answer: 0, explanation: "Wi-Fi Radio Wave ব্যবহার করে, সাধারণত 2.4 GHz বা 5 GHz ফ্রিকোয়েন্সিতে। IEEE 802.11 স্ট্যান্ডার্ড অনুসরণ করে।" },
  { q: "Bluetooth কোন প্রযুক্তি ব্যবহার করে?", options: ["Infrared","Microwave","Fiber Optic","Radio Wave (2.4 GHz)"], answer: 3, explanation: "Bluetooth 2.4 GHz Radio Wave ব্যবহার করে। সাধারণত ১০ মিটারের মধ্যে ডিভাইস সংযুক্ত করতে ব্যবহৃত হয়।" },
  { q: "কোন মাধ্যম সবচেয়ে দ্রুত ডেটা পরিবহন করে?", options: ["Coaxial Cable","Fiber Optic Cable","Twisted Pair","Radio Wave"], answer: 1, explanation: "Fiber Optic Cable সবচেয়ে দ্রুত — আলোর গতিতে ডেটা পাঠায়। ব্যান্ডউইথ অনেক বেশি এবং দীর্ঘ দূরত্বে কোনো সংকেত দুর্বলতা নেই।" },
  { q: "Infrared (IR) যোগাযোগের সীমাবদ্ধতা কী?", options: ["দেয়াল ভেদ করতে পারে না, দৃষ্টির মধ্যে থাকতে হয়","দামি","শুধু ইন্টারনেটে ব্যবহার্য","কম গতি"], answer: 0, explanation: "Infrared দেয়াল বা অন্য বাধা অতিক্রম করতে পারে না — Line-of-Sight প্রয়োজন। রিমোট কন্ট্রোলে ব্যবহৃত হয়।" },
  { q: "Microwave যোগাযোগে কোন ধরনের সমস্যা হতে পারে?", options: ["তার ছিঁড়ে যাওয়া","দাম বেশি","শুধু স্বল্প দূরত্বে কার্যকর","বায়ুমণ্ডলীয় প্রতিবন্ধকতা ও Line-of-Sight প্রয়োজন"], answer: 3, explanation: "Microwave যোগাযোগে Line-of-Sight প্রয়োজন — পথে বাধা থাকলে সংকেত বিঘ্নিত হয়। বৃষ্টি ও বায়ুমণ্ডলীয় প্রতিকূলতায় সংকেত দুর্বল হয়।" },
];
export default function CommunicationMediaQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#7c3aed";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — কমিউনিকেশন মাধ্যম</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f5f3ff",border:"1px solid #ddd6fe",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
