"use client";
import { useState } from "react";
const questions = [
  { q: "TCP/IP-এর পূর্ণরূপ কী?", options: ["Transmission Control Protocol / Internet Protocol","Transfer Control Program / Interface Protocol","Transmission Communication Protocol / IP","Terminal Control Protocol / Internet Program"], answer: 0, explanation: "TCP/IP = Transmission Control Protocol / Internet Protocol। ইন্টারনেটের মূল প্রোটোকল — দুটি আলাদা প্রোটোকলের সমন্বয়।" },
  { q: "IPv4 Address কত বিটের?", options: ["৬৪ বিটের","১২৮ বিটের","৩২ বিটের","১৬ বিটের"], answer: 2, explanation: "IPv4 (Internet Protocol version 4) = ৩২ বিট। চারটি অক্টেটে লেখা হয় (যেমন: 192.168.1.1)। সর্বোচ্চ ২³² = ৪.৩ বিলিয়ন Address।" },
  { q: "IPv6 Address কত বিটের?", options: ["৬৪ বিটের","১২৮ বিটের","৩২ বিটের","২৫৬ বিটের"], answer: 1, explanation: "IPv6 (Internet Protocol version 6) = ১২৮ বিট। IPv4 Address ফুরিয়ে যাওয়ায় তৈরি। ২¹²⁸ ≈ ৩.৪ × ১০³⁸ Address সম্ভব।" },
  { q: "DNS-এর কাজ কী?", options: ["ডেটা এনক্রিপ্ট করা","ওয়েবসাইট তৈরি করা","ইমেইল পাঠানো","Domain Name-কে IP Address-এ রূপান্তর করা"], answer: 3, explanation: "DNS = Domain Name System। মানুষের পাঠযোগ্য Domain Name (যেমন: google.com) কে কম্পিউটারের IP Address (142.250.x.x)-এ রূপান্তর করে।" },
  { q: "HTTP কোন কাজে ব্যবহৃত হয়?", options: ["ইমেইল পাঠানো","ফাইল ট্রান্সফার","ওয়েব পেজ ব্রাউজিং ও ডেটা স্থানান্তর","চ্যাটিং"], answer: 2, explanation: "HTTP (HyperText Transfer Protocol) ওয়েব ব্রাউজারে ওয়েব পেজ দেখতে ব্যবহৃত হয়। HTTPS = HTTP + SSL (নিরাপদ সংস্করণ)।" },
  { q: "FTP কোন কাজে ব্যবহৃত হয়?", options: ["সার্ভার থেকে ফাইল আপলোড/ডাউনলোড","ওয়েব ব্রাউজিং","ইমেইল পাঠানো","ভিডিও স্ট্রিমিং"], answer: 0, explanation: "FTP (File Transfer Protocol) সার্ভার ও ক্লায়েন্টের মধ্যে ফাইল আপলোড ও ডাউনলোড করতে ব্যবহৃত হয়।" },
  { q: "ইমেইল পাঠাতে কোন প্রোটোকল ব্যবহার হয়?", options: ["HTTP","FTP","DNS","SMTP"], answer: 3, explanation: "SMTP (Simple Mail Transfer Protocol) ইমেইল পাঠাতে ব্যবহৃত হয়। POP3/IMAP ইমেইল পেতে ব্যবহৃত হয়।" },
  { q: "ISP-এর পূর্ণরূপ কী?", options: ["Internet System Program","Internet Service Provider","Internal Service Protocol","International Service Provider"], answer: 1, explanation: "ISP = Internet Service Provider। যে প্রতিষ্ঠান ইন্টারনেট সংযোগ দেয়। বাংলাদেশে: Grameenphone, Robi, Banglalink ইত্যাদি।" },
  { q: "IP Address-এর কাজ কী?", options: ["নেটওয়ার্কে প্রতিটি ডিভাইসকে অদ্বিতীয়ভাবে চিহ্নিত করা","ডেটা এনক্রিপ্ট করা","ওয়েবসাইটের নাম দেওয়া","নেটওয়ার্কের গতি বাড়ানো"], answer: 0, explanation: "IP Address (Internet Protocol Address) নেটওয়ার্কে প্রতিটি ডিভাইসের অদ্বিতীয় ঠিকানা — যেন বাড়ির ডাক ঠিকানা। এটি ছাড়া ডেটা সঠিক গন্তব্যে পৌঁছায় না।" },
  { q: "Router-এর কাজ কী?", options: ["শুধু LAN সংযোগ","Wi-Fi সংকেত তৈরি করা","ডেটা সংরক্ষণ করা","বিভিন্ন নেটওয়ার্কের মধ্যে ডেটা প্যাকেট পাঠানো"], answer: 3, explanation: "Router বিভিন্ন নেটওয়ার্কের মধ্যে ডেটা প্যাকেট পাঠায় — সঠিক পথ নির্বাচন করে (Routing)। বাড়ির Wi-Fi Router ইন্টারনেট ও স্থানীয় নেটওয়ার্কের মধ্যে সংযোগ রাখে।" },
];
export default function InternetProtocolQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#ca8a04";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — ইন্টারনেট ও প্রোটোকল</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#fefce8",border:"1px solid #fef08a",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
