"use client";
import { useState } from "react";
const questions = [
  { q: "ই-গভর্ন্যান্স (e-Governance) কী?", options: ["তথ্য প্রযুক্তি ব্যবহার করে সরকারি সেবা প্রদান","শুধু ইন্টারনেট ব্যবহার","কম্পিউটার প্রশিক্ষণ","অনলাইন কেনাকাটা"], answer: 0, explanation: "e-Governance হলো ICT ব্যবহার করে সরকারি সেবা, তথ্য ও কার্যক্রম নাগরিকদের কাছে পৌঁছে দেওয়া। যেমন: পাসপোর্ট আবেদন, জন্মনিবন্ধন অনলাইনে।" },
  { q: "টেলিমেডিসিন কী?", options: ["রোবট দিয়ে অপারেশন","শুধু ফোনে পরামর্শ","ICT ব্যবহার করে দূর থেকে চিকিৎসা সেবা","হাসপাতালের ওয়েবসাইট"], answer: 2, explanation: "টেলিমেডিসিন হলো ICT ব্যবহার করে দূর থেকে ডাক্তারের পরামর্শ, রোগ নির্ণয় ও চিকিৎসা সেবা গ্রহণ। বাংলাদেশে গ্রামাঞ্চলে বিশেষ উপকারী।" },
  { q: "ডিজিটাল বাংলাদেশ রূপকল্প কোন সাল লক্ষ্যমাত্রা ছিল?", options: ["২০৩০","২০২১","২০৪১","২০৫০"], answer: 1, explanation: "ডিজিটাল বাংলাদেশ রূপকল্প ২০২১ — বাংলাদেশের স্বাধীনতার সুবর্ণজয়ন্তী বছরে ডিজিটাল বাংলাদেশ গড়ার লক্ষ্যমাত্রা নির্ধারিত ছিল।" },
  { q: "ই-কমার্স (e-Commerce) কী?", options: ["শুধু অনলাইনে বিজ্ঞাপন","শুধু পণ্য দেখা","ব্যাংকিং সেবা","ইন্টারনেটের মাধ্যমে পণ্য ও সেবা ক্রয়-বিক্রয়"], answer: 3, explanation: "e-Commerce = Electronic Commerce। ইন্টারনেটের মাধ্যমে পণ্য ও সেবা ক্রয়-বিক্রয়। Daraz, Chaldal, Shajgoj — বাংলাদেশে জনপ্রিয় ই-কমার্স।" },
  { q: "দূরশিক্ষণ (E-learning) কীভাবে কাজ করে?", options: ["শুধু বই পড়া","টেলিভিশনে ক্লাস","ICT ব্যবহারে ঘরে বসে শিক্ষা গ্রহণ","শুধু ভিডিও দেখা"], answer: 2, explanation: "E-learning ICT ব্যবহার করে ইন্টারনেটে ভিডিও ক্লাস, ইন্টারেক্টিভ কুইজ, ডিজিটাল বই দিয়ে শিক্ষা দেয়। Coursera, Khan Academy, EduSocial BD এর উদাহরণ।" },
  { q: "স্মার্ট বাংলাদেশ রূপকল্প কোন সাল?", options: ["২০৪১","২০৩০","২০২৫","২০৫০"], answer: 0, explanation: "স্মার্ট বাংলাদেশ রূপকল্প ২০৪১ — ডিজিটাল বাংলাদেশের পরবর্তী ধাপ। স্মার্ট সিটিজেন, স্মার্ট গভর্নমেন্ট, স্মার্ট ইকোনমি, স্মার্ট সোসাইটি।" },
  { q: "ইউনিয়ন ডিজিটাল সেন্টার (UDC) কোথায় স্থাপিত হয়েছে?", options: ["শুধু জেলা শহরে","শুধু ঢাকায়","বিভাগীয় শহরে","বাংলাদেশের প্রতিটি ইউনিয়নে"], answer: 3, explanation: "ইউনিয়ন ডিজিটাল সেন্টার (UDC) বাংলাদেশের প্রতিটি ইউনিয়নে স্থাপিত হয়েছে। গ্রামের মানুষ এখানে ডিজিটাল সেবা পায়।" },
  { q: "ই-স্বাস্থ্য (e-Health) কোন ক্ষেত্রে ICT ব্যবহার?", options: ["শুধু হাসপাতালের ওয়েবসাইট","স্বাস্থ্য সেবায় ICT প্রয়োগ","ওষুধ তৈরিতে","শুধু রেকর্ড সংরক্ষণ"], answer: 1, explanation: "e-Health হলো স্বাস্থ্য সেবায় ICT প্রয়োগ — টেলিমেডিসিন, ইলেকট্রনিক স্বাস্থ্য রেকর্ড, অনলাইন ওষুধ কেনা সবই e-Health-এর অংশ।" },
  { q: "ফ্রিল্যান্সিং বিশ্বগ্রামে কোন ধরনের কর্মসংস্থান?", options: ["অনলাইনে দূর থেকে কাজ করা","স্থায়ী চাকরি","শুধু দেশে কাজ","অফিসে যাওয়ার চাকরি"], answer: 0, explanation: "ফ্রিল্যান্সিং বিশ্বগ্রামের একটি কর্মসংস্থানের রূপ — ইন্টারনেটে বিশ্বের যেকোনো প্রান্তের ক্লায়েন্টের কাজ করা যায়। বাংলাদেশ ফ্রিল্যান্সিংয়ে শীর্ষ দেশগুলোর একটি।" },
  { q: "ই-সার্ভিস (e-Service)-এর উদাহরণ কোনটি?", options: ["ডাকঘরে চিঠি পাঠানো","ব্যাংকে সশরীরে যাওয়া","হাতে ফর্ম পূরণ করা","অনলাইনে পাসপোর্ট আবেদন"], answer: 3, explanation: "e-Service-এর উদাহরণ: অনলাইনে পাসপোর্ট আবেদন, জন্মনিবন্ধন, ভর্তি আবেদন, বিদ্যুৎ বিল পরিশোধ — ঘরে বসেই সরকারি সেবা।" },
];
export default function DigitalBangladeshQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#16a34a";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — ডিজিটাল বাংলাদেশ</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f0fdf4",border:"1px solid #bbf7d0",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
