"use client";
import { useState } from "react";
const questions = [
  { q: "Hacking-এর ক্ষেত্রে 'White Hat Hacker' কারা?", options: ["নৈতিক হ্যাকার যারা নিরাপত্তা পরীক্ষা করে","অপরাধী হ্যাকার","গোয়েন্দা সংস্থার হ্যাকার","অজ্ঞাতপরিচয় হ্যাকার"], answer: 0, explanation: "White Hat Hacker = নৈতিক হ্যাকার — প্রতিষ্ঠানের অনুমতিতে নিরাপত্তা দুর্বলতা খোঁজে ও ঠিক করে। Black Hat = অপরাধী হ্যাকার। Grey Hat = মাঝামাঝি।" },
  { q: "Computer Virus কীভাবে ছড়ায়?", options: ["নিজে নিজে নেটওয়ার্কে","শুধু ইন্টারনেটে","অন্য প্রোগ্রামে সংযুক্ত হয়ে, ফাইল ও ই-মেইলের মাধ্যমে","শুধু USB-তে"], answer: 2, explanation: "Computer Virus অন্য প্রোগ্রামে সংযুক্ত হয়ে ছড়ায় — ইনফেক্টেড ফাইল, ই-মেইল অ্যাটাচমেন্ট, USB, ডাউনলোডের মাধ্যমে।" },
  { q: "Phishing কী?", options: ["কম্পিউটারে ভাইরাস","ভুয়া ই-মেইল/ওয়েবসাইট দিয়ে তথ্য চুরির প্রতারণা","নেটওয়ার্ক হ্যাকিং","স্প্যাম মেইল"], answer: 1, explanation: "Phishing = ভুয়া ই-মেইল বা ওয়েবসাইট ব্যবহার করে ব্যবহারকারীকে ধোঁকা দিয়ে পাসওয়ার্ড, ব্যাংক তথ্য চুরি।" },
  { q: "Firewall কীভাবে কাজ করে?", options: ["ভাইরাস মুছে দেয়","পাসওয়ার্ড সংরক্ষণ করে","ডেটা ব্যাকআপ নেয়","অননুমোদিত নেটওয়ার্ক ট্র্যাফিক ব্লক করে"], answer: 3, explanation: "Firewall নেটওয়ার্কে প্রবেশকারী ও বের হওয়া ট্র্যাফিক পর্যবেক্ষণ করে এবং নির্ধারিত নিয়ম অনুযায়ী অননুমোদিত ট্র্যাফিক ব্লক করে।" },
  { q: "Worm ও Virus-এর পার্থক্য কী?", options: ["Worm বেশি ক্ষতিকর","একই জিনিস","Worm নিজে নিজে নেটওয়ার্কে ছড়ায়; Virus অন্য প্রোগ্রামে সংযুক্ত","Virus দ্রুততর"], answer: 2, explanation: "Worm: নিজে নিজে নেটওয়ার্কে ছড়ায়, কোনো হোস্ট প্রোগ্রাম দরকার নেই। Virus: অন্য প্রোগ্রামে সংযুক্ত হয়ে ছড়ায়।" },
  { q: "Ransomware কী ক্ষতি করে?", options: ["ফাইল এনক্রিপ্ট করে মুক্তিপণ দাবি করে","শুধু ব্যাটারি নষ্ট করে","ইন্টারনেট বন্ধ করে","শুধু স্ক্রিন ব্লক করে"], answer: 0, explanation: "Ransomware ভুক্তভোগীর ফাইল এনক্রিপ্ট (লক) করে দেয় এবং মুক্তিপণ (Ransom) পেলে ডিক্রিপ্ট করার প্রতিশ্রুতি দেয়। WannaCry বিখ্যাত Ransomware।" },
  { q: "Strong Password-এর বৈশিষ্ট্য কোনটি?", options: ["শুধু নাম ব্যবহার","সংক্ষিপ্ত পাসওয়ার্ড","জন্মতারিখ ব্যবহার","বড় ও ছোট হরফ, সংখ্যা ও বিশেষ চিহ্নের মিশ্রণ"], answer: 3, explanation: "Strong Password: কমপক্ষে 12 অক্ষর, বড় হরফ (A-Z), ছোট হরফ (a-z), সংখ্যা (0-9) ও বিশেষ চিহ্ন (!@#$) — সব মিলিয়ে।" },
  { q: "Encryption কী?", options: ["ডেটা মুছে ফেলা","ডেটা কোডে রূপান্তর করে অপঠনযোগ্য করা","ডেটা সংকোচন","ডেটা ব্যাকআপ"], answer: 1, explanation: "Encryption ডেটাকে বিশেষ অ্যালগরিদমে কোডে (Cipher text) রূপান্তর করে — শুধু সঠিক Key দিয়ে Decrypt করে পড়া যায়। HTTPS, WhatsApp Encryption ব্যবহার করে।" },
  { q: "Spam কী?", options: ["অবাঞ্ছিত ও অপ্রয়োজনীয় বার্তা বা ই-মেইল","ভাইরাস","হ্যাকিং","ফিশিং"], answer: 0, explanation: "Spam হলো অবাঞ্ছিত বার্তা — সাধারণত বিজ্ঞাপন বা প্রতারণামূলক ই-মেইল যা অনেক মানুষের কাছে পাঠানো হয়। Spam Filter এগুলো আলাদা করে।" },
  { q: "Two-Factor Authentication (2FA) কীভাবে সুরক্ষা দেয়?", options: ["শুধু পাসওয়ার্ড","শুধু OTP","শুধু আঙুলের ছাপ","পাসওয়ার্ডের পাশাপাশি দ্বিতীয় যাচাই স্তর (OTP/বায়োমেট্রিক) যোগ করে"], answer: 3, explanation: "2FA = দুটি স্তরে পরিচয় যাচাই: পাসওয়ার্ড + OTP/Authenticator App/Biometric। পাসওয়ার্ড চুরি হলেও দ্বিতীয় স্তর সুরক্ষা দেয়।" },
];
export default function CybersecurityQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#ca8a04";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — সাইবার নিরাপত্তা</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#fefce8",border:"1px solid #fef08a",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
