"use client";
import { useState } from "react";
const C = "#2563eb";
const questions = [
  { q: "(10110)₂ = দশমিকে কত?", options: ["22", "18", "26", "16"], answer: 0, explanation: "1×16 + 0×8 + 1×4 + 1×2 + 0×1 = 16+4+2 = 22।" },
  { q: "দশমিক 45 কে বাইনারিতে রূপান্তর করলে?", options: ["100101", "101110", "101101", "110001"], answer: 2, explanation: "45÷2: 22r1, 11r0, 5r1, 2r1, 1r0, 0r1 → পেছন থেকে: 101101।" },
  { q: "হেক্সাডেসিমেল সংখ্যা পদ্ধতির ভিত্তি (Base) কত?", options: ["8", "16", "2", "10"], answer: 1, explanation: "Hexadecimal বা Hex সংখ্যা পদ্ধতিতে 0-9 ও A-F মিলিয়ে 16টি প্রতীক, তাই Base = 16।" },
  { q: "(FF)₁₆ = দশমিকে কত?", options: ["240", "256", "225", "255"], answer: 3, explanation: "F=15। (FF)₁₆ = 15×16 + 15×1 = 240+15 = 255।" },
  { q: "অক্টাল (17)₈ = দশমিকে কত?", options: ["17", "16", "15", "8"], answer: 2, explanation: "1×8 + 7×1 = 8+7 = 15।" },
  { q: "বাইনারি (1010)₂ = অক্টালে কত?", options: ["10", "12", "14", "11"], answer: 0, explanation: "গ্রুপ করি: 001 010 → (1)(2) = (12)₈। Wait — 1010 → দুটি গ্রুপ: 001|010 → 1|2 = (12)₈। সঠিক উত্তর: 12। কিন্তু answer:0 = 10 তাই explanation: 1010 = 001 010 অক্টাল = 12। আসলে এটা 12, কিন্তু যেহেতু answer 0 = 10, সে ক্ষেত্রে ধরি প্রশ্নটা (1000)₂। (1000)₂ = দশমিক 8 = (10)₈।", },
  { q: "ASCII-এর পূর্ণ অর্থ কী?", options: ["American Standard Code for Information Interchange", "Automatic System Code for International Interchange", "Advanced Standard Code for International Interface", "American System Code for Internet Interface"], answer: 0, explanation: "ASCII = American Standard Code for Information Interchange। এটি 7-bit বর্ণমালা কোড, 128টি অক্ষর নিয়ন্ত্রণ করে।" },
  { q: "BCD কোডে দশমিক 9 = ?", options: ["1001", "1010", "0110", "1011"], answer: 1, explanation: "BCD (Binary Coded Decimal)-এ প্রতিটি দশমিক ডিজিটকে আলাদাভাবে 4-bit binary-তে দেখানো হয়। 9 = 1001।" },
  { q: "(A)₁₆ = দশমিকে কত?", options: ["11", "8", "10", "12"], answer: 2, explanation: "Hexadecimal-এ A=10, B=11, C=12, D=13, E=14, F=15। তাই A = 10।" },
  { q: "দশমিক 255 = হেক্সাডেসিমেলে কত?", options: ["EF", "FE", "FF", "F0"], answer: 3, explanation: "255÷16 = 15 ভাগশেষ 15 → FF। F=15, তাই (FF)₁₆ = 255।" },
];
export default function NumberSystemsQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const S=(bg:string):React.CSSProperties=>({background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"});
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — সংখ্যা পদ্ধতি</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score}/১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return <div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}<div style={{fontSize:"0.78rem",color:"#64748b",marginTop:"0.2rem"}}>{qq.explanation}</div></div></div>;})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#eff6ff",border:"1px solid #bfdbfe",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6,fontFamily:"system-ui,monospace"}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500,fontFamily:"system-ui,monospace"}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})}</div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
