"use client";
import { useState } from "react";
const questions = [
  { q: "ডেটা কমিউনিকেশনের কয়টি মূল উপাদান আছে?", options: ["৫টি","৩টি","৪টি","৬টি"], answer: 0, explanation: "ডেটা কমিউনিকেশনের ৫টি মূল উপাদান: ১. প্রেরক (Sender) ২. প্রাপক (Receiver) ৩. বার্তা (Message) ৪. মাধ্যম (Medium) ৫. প্রোটোকল (Protocol)।" },
  { q: "Simplex ট্রান্সমিশন মোডে ডেটা কোন দিকে যায়?", options: ["দুদিকে","একই সময়ে দুদিকে","শুধু একদিকে","পর্যায়ক্রমে দুদিকে"], answer: 2, explanation: "Simplex: ডেটা শুধু একদিকে যায়। যেমন: রেডিও, টেলিভিশন — সম্প্রচার কেন্দ্র পাঠায়, দর্শক শুধু গ্রহণ করে।" },
  { q: "Half-Duplex ট্রান্সমিশনের উদাহরণ কোনটি?", options: ["টেলিফোন","Walkie-Talkie","রেডিও","টেলিভিশন"], answer: 1, explanation: "Half-Duplex: দুদিকে ডেটা যায় কিন্তু একই সময়ে নয়। Walkie-Talkie-তে একজন কথা বললে অপরজন শোনে।" },
  { q: "Full-Duplex ট্রান্সমিশনের উদাহরণ কোনটি?", options: ["Walkie-Talkie","রেডিও","টেলিভিশন","টেলিফোন"], answer: 3, explanation: "Full-Duplex: একই সময়ে দুদিকে ডেটা যায়। টেলিফোনে দুজন একই সময়ে কথা বলতে ও শুনতে পারেন।" },
  { q: "Bandwidth কী পরিমাপ করে?", options: ["নেটওয়ার্কের আকার","ক্যাবলের দৈর্ঘ্য","ডেটা পরিবহনের ক্ষমতা (প্রতি সেকেন্ডে)","সংযুক্ত ডিভাইসের সংখ্যা"], answer: 2, explanation: "Bandwidth হলো কোনো চ্যানেলে প্রতি সেকেন্ডে কতটুকু ডেটা পরিবহন করা যায় তার পরিমাপ। একক: bps, Kbps, Mbps, Gbps।" },
  { q: "1 Gbps = কত Mbps?", options: ["১০০০ Mbps","১০০ Mbps","১০ Mbps","১০,০০০ Mbps"], answer: 0, explanation: "1 Gbps (Gigabit per second) = 1000 Mbps (Megabit per second)। ডেটা ট্রান্সমিশন রেটের একক।" },
  { q: "Analog Signal ও Digital Signal-এর পার্থক্য কী?", options: ["Analog দ্রুততর","Digital তরঙ্গাকার","কোনো পার্থক্য নেই","Analog তরঙ্গাকার ও ক্রমাগত; Digital 0 ও 1 ভিত্তিক"], answer: 3, explanation: "Analog Signal তরঙ্গাকার ও ক্রমাগত পরিবর্তনশীল। Digital Signal শুধু দুটি মান (0 বা 1)। কম্পিউটার Digital Signal ব্যবহার করে।" },
  { q: "Modem-এর কাজ কী?", options: ["শুধু ডেটা প্রেরণ","Analog ও Digital সংকেত পরস্পর রূপান্তর","শুধু ইন্টারনেট সংযোগ","ডেটা সংরক্ষণ"], answer: 1, explanation: "Modem = MOdulator-DEModulator। Modulation: Digital → Analog (পাঠাতে), Demodulation: Analog → Digital (পেতে)।" },
  { q: "Protocol কী?", options: ["নেটওয়ার্কে ডেটা আদান-প্রদানের নিয়মকানুন","একটি ডিভাইস","ক্যাবলের ধরন","নেটওয়ার্কের আকার"], answer: 0, explanation: "Protocol হলো নেটওয়ার্কে যোগাযোগের জন্য নির্ধারিত নিয়মকানুন। এটি ছাড়া দুটি ডিভাইস পরস্পর বুঝতে পারে না।" },
  { q: "ডেটা ট্রান্সমিশন মোড কত ধরনের?", options: ["২ ধরনের","৪ ধরনের","৫ ধরনের","৩ ধরনের"], answer: 3, explanation: "তিন ধরনের ট্রান্সমিশন মোড: ১. Simplex (একমুখী), ২. Half-Duplex (পর্যায়ক্রমে দুমুখী), ৩. Full-Duplex (একসাথে দুমুখী)।" },
];
export default function DataCommunicationQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#0284c7";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — ডেটা কমিউনিকেশন</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f0f9ff",border:"1px solid #bae6fd",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
