"use client";
import { useState } from "react";
const questions = [
  { q: "CSS-এর পূর্ণরূপ কী?", options: ["Cascading Style Sheets","Colored Style Sheets","Computer Style Sheets","Creative Style Sheets"], answer: 0, explanation: "CSS = Cascading Style Sheets। HTML-এর উপস্থাপনা ও বিন্যাস নিয়ন্ত্রণের ভাষা।" },
  { q: "CSS Class Selector চেনার চিহ্ন কোনটি?", options: ["# (হ্যাশ)","* (তারা)",". (ডট)","@ (এট)"], answer: 2, explanation: "CSS-এ Class Selector সবসময় . (ডট) দিয়ে শুরু হয়। যেমন: .myClass { color: red; }।" },
  { q: "CSS ID Selector চেনার চিহ্ন কোনটি?", options: [". (ডট)","# (হ্যাশ)","* (তারা)","! (বিস্ময়)"], answer: 1, explanation: "CSS-এ ID Selector সবসময় # (হ্যাশ) দিয়ে শুরু হয়। যেমন: #myId { font-size: 20px; }।" },
  { q: "ইনলাইন CSS কোথায় লেখা হয়?", options: ["<head>-এর <style> ট্যাগে","আলাদা .css ফাইলে","JavaScript-এ","সরাসরি HTML ট্যাগের style attribute-এ"], answer: 3, explanation: "Inline CSS সরাসরি HTML ট্যাগে লেখা হয়: <p style='color:red;'>। এটি শুধু সেই উপাদানে প্রযোজ্য।" },
  { q: "External CSS কীভাবে HTML পেজে যুক্ত করা হয়?", options: ["<style src='style.css'>","<css file='style.css'>","<link rel='stylesheet' href='style.css'>","<import css='style.css'>"], answer: 2, explanation: "<link rel='stylesheet' href='style.css'> দিয়ে HTML-এর <head>-এ External CSS যুক্ত করা হয়।" },
  { q: "CSS Box Model-এ বাইরে থেকে ভেতরের সঠিক ক্রম কোনটি?", options: ["Margin → Border → Padding → Content","Content → Padding → Border → Margin","Border → Margin → Padding → Content","Padding → Margin → Content → Border"], answer: 0, explanation: "CSS Box Model বাইরে থেকে: Margin (সবচেয়ে বাইরে) → Border → Padding → Content (সবচেয়ে ভেতরে)।" },
  { q: "CSS-এ সব উপাদান নির্বাচন করতে কোন Selector ব্যবহার হয়?", options: ["all { }","every { }","html { }","* (Universal Selector)"], answer: 3, explanation: "* হলো Universal Selector যা পেজের সব HTML উপাদান নির্বাচন করে।" },
  { q: "p { color: blue; } — এখানে 'p' কী?", options: ["Property","Selector","Value","Rule"], answer: 1, explanation: "'p' হলো CSS Selector — কোন HTML উপাদানে স্টাইল প্রযোজ্য হবে তা নির্দেশ করে।" },
  { q: "CSS-এ font-size: 16px; এখানে 'font-size' কী?", options: ["Property","Selector","Value","Attribute"], answer: 0, explanation: "'font-size' হলো CSS Property — কোন বৈশিষ্ট্য পরিবর্তন করা হবে তা নির্দেশ করে।" },
  { q: "তিন ধরনের CSS-এর মধ্যে সর্বোচ্চ Priority (অগ্রাধিকার) কোনটির?", options: ["Internal CSS","External CSS","সবগুলো সমান","Inline CSS"], answer: 3, explanation: "Priority: Inline > Internal > External। Inline CSS সবচেয়ে নির্দিষ্ট তাই এর অগ্রাধিকার সর্বোচ্চ।" },
];
export default function CSSQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#7c3aed";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — CSS</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f5f3ff",border:"1px solid #ddd6fe",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
