"use client";
import { useState } from "react";
const questions = [
  { q: "Star Topology-তে সব কম্পিউটার কীসের সাথে সংযুক্ত?", options: ["কেন্দ্রীয় Hub বা Switch-এর সাথে","একটি মূল তারের সাথে","পরস্পরের সাথে সরাসরি","বৃত্তাকারভাবে"], answer: 0, explanation: "Star Topology-তে প্রতিটি কম্পিউটার কেন্দ্রীয় Hub বা Switch-এর সাথে আলাদাভাবে সংযুক্ত। এটি সবচেয়ে জনপ্রিয় টপোলজি।" },
  { q: "Bus Topology-তে একটি কম্পিউটার নষ্ট হলে কী ঘটে?", options: ["বাকি কম্পিউটার চলতে থাকে","সব নেটওয়ার্ক বন্ধ হয়","শুধু সেই কম্পিউটার বন্ধ হয়","নেটওয়ার্ক ধীর হয়"], answer: 2, explanation: "Bus Topology-তে একটি কম্পিউটার নষ্ট হলে বাকি কম্পিউটার চলতে থাকে। কিন্তু মূল ক্যাবল (Bus) নষ্ট হলে পুরো নেটওয়ার্ক বন্ধ হয়।" },
  { q: "Ring Topology-তে ডেটা কীভাবে পরিবহন হয়?", options: ["Hub থেকে সরাসরি","Token Passing পদ্ধতিতে বৃত্তাকারে","Broadcast পদ্ধতিতে","যেকোনো পথে"], answer: 1, explanation: "Ring Topology-তে Token Passing পদ্ধতিতে ডেটা বৃত্তাকারে একদিকে পাঠানো হয়। Token ধরে থাকা কম্পিউটার ডেটা পাঠাতে পারে।" },
  { q: "Mesh Topology-র সবচেয়ে বড় সুবিধা কী?", options: ["সবচেয়ে সস্তা","স্থাপনা সহজ","কম ক্যাবল লাগে","সর্বোচ্চ নির্ভরযোগ্যতা — একটি পথ নষ্ট হলেও অন্য পথে যায়"], answer: 3, explanation: "Mesh Topology-তে সব ডিভাইস পরস্পরের সাথে সংযুক্ত। একটি সংযোগ নষ্ট হলেও অন্য পথে ডেটা যেতে পারে — সর্বোচ্চ নির্ভরযোগ্যতা।" },
  { q: "Tree Topology কোন দুটি টপোলজির সমন্বয়?", options: ["Ring + Mesh","Star + Ring","Bus + Star","Bus + Mesh"], answer: 2, explanation: "Tree Topology হলো Bus ও Star-এর সমন্বয়। কেন্দ্রীয় Bus-এ একাধিক Star Topology সংযুক্ত থাকে। Hierarchical কাঠামো তৈরি করে।" },
  { q: "Star Topology-তে Hub নষ্ট হলে কী হয়?", options: ["পুরো নেটওয়ার্ক বন্ধ হয়","শুধু কিছু কম্পিউটার বন্ধ হয়","কিছুই হয় না","ধীর হয়"], answer: 0, explanation: "Star Topology-তে Hub/Switch নষ্ট হলে পুরো নেটওয়ার্ক বন্ধ হয় — এটি এই টপোলজির প্রধান দুর্বলতা।" },
  { q: "কোন টপোলজিতে সবচেয়ে বেশি ক্যাবল প্রয়োজন?", options: ["Bus Topology","Ring Topology","Star Topology","Mesh Topology"], answer: 3, explanation: "Mesh Topology-তে সব ডিভাইস পরস্পরের সাথে সংযুক্ত, তাই n টি ডিভাইসের জন্য n(n-1)/2 সংযোগ লাগে — সবচেয়ে বেশি ক্যাবল।" },
  { q: "Bus Topology-র প্রধান সুবিধা কোনটি?", options: ["সবচেয়ে নির্ভরযোগ্য","স্থাপনা সহজ ও ক্যাবল কম লাগে","Hub দরকার নেই এবং দামও কম","দ্রুততম"], answer: 1, explanation: "Bus Topology-তে একটি মাত্র তারে সব ডিভাইস সংযুক্ত — স্থাপনা সহজ, ক্যাবল কম লাগে। তবে মূল তার নষ্ট হলে সব বন্ধ।" },
  { q: "কোন টপোলজি সবচেয়ে বেশি ব্যবহৃত হয়?", options: ["Star Topology","Bus Topology","Ring Topology","Mesh Topology"], answer: 0, explanation: "Star Topology সবচেয়ে জনপ্রিয় — একটি ডিভাইস নষ্ট হলে বাকি চলে, সমস্যা চিহ্নিত করা সহজ, Hub/Switch সহজলভ্য।" },
  { q: "Topology শব্দটির অর্থ কী?", options: ["নেটওয়ার্কের গতি","নেটওয়ার্কের নিরাপত্তা","নেটওয়ার্কের মাধ্যম","নেটওয়ার্কের ভৌত বিন্যাস বা কাঠামো"], answer: 3, explanation: "Topology মানে নেটওয়ার্কের ভৌত বা যৌক্তিক কাঠামো — কীভাবে ডিভাইসগুলো পরস্পরের সাথে সংযুক্ত তার বিন্যাস।" },
];
export default function NetworkTopologyQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#0891b2";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — নেটওয়ার্ক টপোলজি</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#ecfeff",border:"1px solid #a5f3fc",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
