"use client";
import { useState } from "react";
const questions = [
  { q: "ডিজিটাল বিভাজন (Digital Divide) কী?", options: ["প্রযুক্তিতে সমান সুযোগ না পাওয়া","ইন্টারনেট বন্ধ হওয়া","ডিজিটাল ডিভাইস ভেঙে যাওয়া","সোশ্যাল মিডিয়া বন্ধ"], answer: 0, explanation: "Digital Divide = ডিজিটাল বিভাজন। ধনী-দরিদ্র, শহর-গ্রাম, শিক্ষিত-অশিক্ষিতদের মধ্যে প্রযুক্তি ব্যবহারের সুযোগের পার্থক্য।" },
  { q: "Intellectual Property Rights (IPR) কী?", options: ["কম্পিউটারের অধিকার","ইন্টারনেট সুরক্ষা","মেধাসৃষ্টির আইনগত সুরক্ষা","পেটেন্ট নিবন্ধন"], answer: 2, explanation: "IPR = Intellectual Property Rights। সৃজনশীল কাজের (বই, সফটওয়্যার, উদ্ভাবন) আইনগত সুরক্ষা দেয়। Copyright, Patent, Trademark এর অন্তর্ভুক্ত।" },
  { q: "Copyright লঙ্ঘনের উদাহরণ কোনটি?", options: ["নিজের ছবি শেয়ার করা","অনুমতি ছাড়া সফটওয়্যার কপি করা","বই পড়া","বৈধ সফটওয়্যার কেনা"], answer: 1, explanation: "Copyright লঙ্ঘন: অনুমতি ছাড়া সফটওয়্যার, বই, সিনেমা, সংগীত কপি বা বিতরণ করা। Piracy এক ধরনের Copyright লঙ্ঘন।" },
  { q: "তথ্য প্রযুক্তির ইতিবাচক সামাজিক প্রভাব কোনটি?", options: ["গোপনীয়তা লঙ্ঘন","সাইবার অপরাধ","আসক্তি","শিক্ষার সুযোগ বৃদ্ধি ও জ্ঞান ছড়িয়ে পড়া"], answer: 3, explanation: "ইতিবাচক প্রভাব: শিক্ষার সুযোগ বৃদ্ধি, তাৎক্ষণিক যোগাযোগ, কর্মসংস্থান, ব্যবসার সুযোগ, স্বাস্থ্য সেবার উন্নতি।" },
  { q: "সামাজিক যোগাযোগ মাধ্যমে ব্যক্তিগত তথ্য শেয়ার করা কোন সমস্যা সৃষ্টি করতে পারে?", options: ["কোনো সমস্যা নেই","শুধু বিজ্ঞাপন","গোপনীয়তা লঙ্ঘন ও পরিচয় চুরি","ইন্টারনেট ধীর হওয়া"], answer: 2, explanation: "সামাজিক মাধ্যমে ব্যক্তিগত তথ্য শেয়ার করলে গোপনীয়তা লঙ্ঘন, পরিচয় চুরি (Identity Theft), অনলাইন হয়রানির ঝুঁকি বাড়ে।" },
  { q: "Plagiarism কী?", options: ["অন্যের লেখা বা ধারণা নিজের বলে চালিয়ে দেওয়া","ভাইরাস ছড়ানো","হ্যাকিং","ফিশিং"], answer: 0, explanation: "Plagiarism হলো অন্যের লেখা, ধারণা বা গবেষণা নিজের বলে উপস্থাপন করা — একাডেমিক অসততা। গবেষণা ও শিক্ষা প্রতিষ্ঠানে এটি গুরুতর অপরাধ।" },
  { q: "ICT আসক্তির (Addiction) লক্ষণ কোনটি?", options: ["বেশি বই পড়া","খেলাধুলা করা","ব্যায়াম করা","ডিভাইস ছাড়া অস্থির লাগা, রাত জেগে স্ক্রিনে থাকা"], answer: 3, explanation: "ICT আসক্তির লক্ষণ: ডিভাইস ছাড়া অস্থির লাগা, ঘুম কমে যাওয়া, সামাজিক সম্পর্ক কমে আসা, পড়াশোনায় অমনোযোগ।" },
  { q: "তথ্য প্রযুক্তির নৈতিক ব্যবহার মানে কী?", options: ["যা ইচ্ছে করা","অন্যের ক্ষতি না করে দায়িত্বশীলভাবে ICT ব্যবহার","অন্যের পাসওয়ার্ড ব্যবহার","পাইরেটেড সফটওয়্যার ব্যবহার"], answer: 1, explanation: "নৈতিক ICT ব্যবহার: অন্যের ক্ষতি না করা, গোপনীয়তা রক্ষা করা, Copyright মানা, সত্য তথ্য শেয়ার করা।" },
  { q: "Fake News (ভুয়া তথ্য) সমাজে কী ক্ষতি করে?", options: ["সামাজিক অস্থিরতা, বিভ্রান্তি ও হিংসা ছড়ায়","কিছুই হয় না","শুধু মজার ঘটনা","তথ্যের উন্নতি হয়"], answer: 0, explanation: "Fake News বা ভুয়া তথ্য সামাজিক বিভ্রান্তি, অস্থিরতা ও হিংসা সৃষ্টি করতে পারে। সোশ্যাল মিডিয়ায় দ্রুত ছড়িয়ে পড়ে।" },
  { q: "ডিজিটাল বিভাজন কমাতে কী করা প্রয়োজন?", options: ["শুধু শহরে প্রযুক্তি রাখা","ইন্টারনেট সীমিত করা","দাম বাড়ানো","প্রযুক্তি শিক্ষা ও ইন্টারনেট সংযোগ সবার কাছে পৌঁছানো"], answer: 3, explanation: "Digital Divide কমাতে: সবার জন্য সাশ্রয়ী ইন্টারনেট, ICT শিক্ষার প্রসার, গ্রামাঞ্চলে অবকাঠামো উন্নয়ন প্রয়োজন।" },
];
export default function EthicsSocietyQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#0891b2";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — নৈতিকতা ও সামাজিক প্রভাব</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#ecfeff",border:"1px solid #a5f3fc",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
