"use client";
import { useState } from "react";
const questions = [
  { q: "ডেটা (Data) ও তথ্য (Information)-এর মধ্যে মূল পার্থক্য কী?", options: ["ডেটা প্রক্রিয়াকরণের পর তথ্য হয়","তথ্য প্রক্রিয়াকরণের পর ডেটা হয়","ডেটা ও তথ্য একই","ডেটা সবসময় সংখ্যা"], answer: 0, explanation: "Raw/অপ্রক্রিয়াকৃত ঘটনাকে Data বলে। Data প্রক্রিয়াকরণের পর অর্থবহ হলে তা Information বা তথ্য হয়।" },
  { q: "DBMS-এর পূর্ণরূপ কী?", options: ["Data Base Multiple System","Digital Base Management System","Database Management System","Database Manipulation System"], answer: 2, explanation: "DBMS = Database Management System। ডেটাবেজ তৈরি, সংরক্ষণ, পরিচালনা ও ব্যবহারের সফটওয়্যার।" },
  { q: "নিচের কোনটি DBMS সফটওয়্যারের উদাহরণ?", options: ["MS Word, Excel, PowerPoint","MySQL, Oracle, MS Access","Photoshop, Illustrator","Chrome, Firefox"], answer: 1, explanation: "MySQL, Oracle, SQL Server, MS Access হলো জনপ্রিয় DBMS সফটওয়্যার। MS Word ইত্যাদি Office সফটওয়্যার।" },
  { q: "ডেটাবেজ ব্যবহারের অন্যতম সুবিধা কোনটি?", options: ["ডেটা বারবার নকল হয়","ডেটা সংরক্ষণ কঠিন হয়","একসাথে ব্যবহার সম্ভব নয়","Data Redundancy হ্রাস পায়"], answer: 3, explanation: "ডেটাবেজের প্রধান সুবিধা হলো Data Redundancy (অপ্রয়োজনীয় নকল) হ্রাস পায়, Data Integrity ও Security বৃদ্ধি পায়।" },
  { q: "DBA-এর পূর্ণরূপ কী?", options: ["Data Base Application","Digital Base Analyzer","Database Administrator","Database Authorization"], answer: 2, explanation: "DBA = Database Administrator। ডেটাবেজ ডিজাইন, রক্ষণাবেক্ষণ, নিরাপত্তা ও ব্যবহারকারী ব্যবস্থাপনা তার দায়িত্ব।" },
  { q: "ডেটাবেজে Data Integrity বলতে কী বোঝায়?", options: ["ডেটার সঠিকতা ও নির্ভরযোগ্যতা নিশ্চিত করা","ডেটা মুছে ফেলা","ডেটা এনক্রিপ্ট করা","ডেটা ব্যাকআপ নেওয়া"], answer: 0, explanation: "Data Integrity মানে ডেটাবেজে সংরক্ষিত ডেটা সঠিক, সামঞ্জস্যপূর্ণ এবং নির্ভরযোগ্য থাকা।" },
  { q: "ঐতিহ্যবাহী ফাইল সিস্টেমের তুলনায় ডেটাবেজের সুবিধা কী?", options: ["শুধু একজন ব্যবহার করতে পারে","ডেটা খুঁজে পাওয়া কঠিন","ব্যয় বেশি","Data Sharing সহজ, Redundancy কম, Security বেশি"], answer: 3, explanation: "ডেটাবেজে একই সময়ে একাধিক ব্যবহারকারী Data Share করতে পারে, Redundancy কম এবং Security নিয়ন্ত্রণ করা যায়।" },
  { q: "কোনটি ডেটার উদাহরণ নয়, বরং তথ্যের উদাহরণ?", options: ["সংখ্যা 85","'রাফিয়ার পরীক্ষার ফলাফল: A+'","তারিখ 12-06","নাম 'রাফিয়া'"], answer: 1, explanation: "'রাফিয়ার পরীক্ষার ফলাফল: A+' — এটি প্রক্রিয়াকৃত, অর্থবহ এবং সিদ্ধান্ত নেওয়ার উপযোগী, তাই এটি Information।" },
  { q: "ডেটাবেজের Data Security বলতে কী বোঝায়?", options: ["অনুমোদিত ব্যবহারকারীই শুধু ডেটা অ্যাক্সেস করতে পারবে","ডেটা দ্রুত অ্যাক্সেস করা","ডেটা ব্যাকআপ রাখা","ডেটা মুছে দেওয়া"], answer: 0, explanation: "Data Security নিশ্চিত করে যে শুধুমাত্র অনুমোদিত ব্যবহারকারী ডেটা দেখতে বা পরিবর্তন করতে পারবে।" },
  { q: "নিচের কোন উক্তিটি সঠিক?", options: ["সব ডেটাই তথ্য","তথ্য থেকে ডেটা তৈরি হয়","ডেটা ও তথ্য সমার্থক শব্দ","সব তথ্যই ডেটা থেকে তৈরি, কিন্তু সব ডেটাই তথ্য নয়"], answer: 3, explanation: "ডেটা → প্রক্রিয়াকরণ → তথ্য। কাঁচামাল (ডেটা) থেকে সব পণ্য (তথ্য) হয় না, প্রক্রিয়াকরণ দরকার।" },
];
export default function DatabaseConceptsQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#0284c7";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — ডেটাবেজের ধারণা</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f0f9ff",border:"1px solid #bae6fd",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
