"use client";
import { useState } from "react";
const questions = [
  { q: "LAN-এর পূর্ণরূপ কী?", options: ["Local Area Network","Long Area Network","Large Area Network","Limited Area Network"], answer: 0, explanation: "LAN = Local Area Network। একটি সীমিত এলাকা (ভবন, ক্যাম্পাস) জুড়ে বিস্তৃত নেটওয়ার্ক। পরিসর সাধারণত ১ কিমির মধ্যে।" },
  { q: "WAN-এর বিস্তার কত?", options: ["একটি শহর পর্যন্ত","একটি ভবন পর্যন্ত","দেশ বা মহাদেশ জুড়ে — সীমাহীন","১০ কিমি পর্যন্ত"], answer: 2, explanation: "WAN (Wide Area Network) দেশ বা মহাদেশ জুড়ে বিস্তৃত। ইন্টারনেট হলো পৃথিবীর বৃহত্তম WAN।" },
  { q: "MAN-এর পূর্ণরূপ ও বিস্তার কোনটি?", options: ["Metro Area Node, ১০ কিমি","Metropolitan Area Network, একটি শহর (১০০ কিমি)","Multiple Area Network, ৫০ কিমি","Main Area Node, ২০০ কিমি"], answer: 1, explanation: "MAN = Metropolitan Area Network। একটি শহর বা শহরাঞ্চল জুড়ে বিস্তৃত — সাধারণত ১০০ কিমি পর্যন্ত।" },
  { q: "PAN কোন প্রযুক্তি ব্যবহার করে?", options: ["Ethernet","Fiber Optic","Satellite","Bluetooth বা Infrared"], answer: 3, explanation: "PAN (Personal Area Network) Bluetooth বা Infrared ব্যবহার করে। ব্যক্তিগত ডিভাইস সংযুক্ত করে — সাধারণত ১০ মিটারের মধ্যে।" },
  { q: "ইন্টারনেট কোন ধরনের নেটওয়ার্ক?", options: ["LAN","MAN","WAN (সবচেয়ে বড় WAN)","PAN"], answer: 2, explanation: "ইন্টারনেট বিশ্বের বৃহত্তম WAN (Wide Area Network) — এটি লক্ষ লক্ষ ছোট নেটওয়ার্ককে একত্রে সংযুক্ত করে।" },
  { q: "কোনটির পরিসর সবচেয়ে কম?", options: ["PAN (Personal Area Network)","LAN","MAN","WAN"], answer: 0, explanation: "PAN-এর পরিসর সবচেয়ে কম — মাত্র ১০ মিটার। এর পরে LAN (১ কিমি), MAN (১০০ কিমি), WAN (সীমাহীন)।" },
  { q: "স্কুল বা কলেজের ক্যাম্পাস নেটওয়ার্ক কোন ধরনের?", options: ["WAN","MAN","PAN","LAN"], answer: 3, explanation: "স্কুল, কলেজ বা অফিস ভবনের নেটওয়ার্ক LAN — একটি সীমিত এলাকায় উচ্চগতির সংযোগ।" },
  { q: "Bluetooth earphone সংযোগ কোন ধরনের নেটওয়ার্ক?", options: ["LAN","PAN (Personal Area Network)","MAN","WAN"], answer: 1, explanation: "Bluetooth earphone সংযোগ PAN — ব্যক্তিগত ডিভাইসের মধ্যে স্বল্প দূরত্বের সংযোগ।" },
  { q: "একটি শহরের ক্যাবল টিভি নেটওয়ার্ক কোন ধরনের?", options: ["MAN (Metropolitan Area Network)","LAN","WAN","PAN"], answer: 0, explanation: "শহরব্যাপী ক্যাবল টিভি বা ISP নেটওয়ার্ক MAN — একটি শহর জুড়ে বিস্তৃত।" },
  { q: "LAN, MAN, WAN-এর মধ্যে সবচেয়ে দ্রুত কোনটি?", options: ["WAN","MAN","সবই সমান","LAN (সর্বোচ্চ গতি)"], answer: 3, explanation: "LAN সবচেয়ে দ্রুত — সীমিত এলাকায় Ethernet ব্যবহার করে Gbps গতি পাওয়া যায়। WAN সবচেয়ে ধীর কারণ বিশাল পরিসর।" },
];
export default function NetworkTypesQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#16a34a";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — নেটওয়ার্কের ধরন</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f0fdf4",border:"1px solid #bbf7d0",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
