"use client";
import { useState } from "react";
const questions = [
  { q: "বিশ্বগ্রাম (Global Village) ধারণাটি কে প্রথম প্রবর্তন করেন?", options: ["Marshall McLuhan","Bill Gates","Tim Berners-Lee","Steve Jobs"], answer: 0, explanation: "Marshall McLuhan কানাডিয়ান দার্শনিক ১৯৬০-এর দশকে 'Global Village' ধারণা প্রবর্তন করেন। তিনি বলেন ICT-র কারণে পৃথিবী একটি ছোট গ্রামের মতো।" },
  { q: "বিশ্বগ্রামের মূল ভিত্তি কী?", options: ["পরিবহন ব্যবস্থা","বাণিজ্য","তথ্য ও যোগাযোগ প্রযুক্তি (ICT)","রাজনীতি"], answer: 2, explanation: "বিশ্বগ্রামের মূল ভিত্তি হলো তথ্য ও যোগাযোগ প্রযুক্তি (ICT)। ইন্টারনেট, ই-মেইল, ভিডিও কল সবাইকে কাছে এনেছে।" },
  { q: "বিশ্বগ্রামের উপাদান কোনটি নয়?", options: ["যোগাযোগ","ভৌত পরিবহন (সড়ক/রেল)","কর্মসংস্থান","চিকিৎসা সেবা"], answer: 1, explanation: "বিশ্বগ্রামের উপাদান: যোগাযোগ, কর্মসংস্থান, শিক্ষা, চিকিৎসা, গবেষণা, সংস্কৃতি ও বিনোদন। ভৌত পরিবহন এর অংশ নয়।" },
  { q: "ই-মেইল কোন ধরনের যোগাযোগ মাধ্যম?", options: ["সমকালীন (Synchronous)","কোনোটাই নয়","দুটোই","অসমকালীন (Asynchronous)"], answer: 3, explanation: "ই-মেইল অসমকালীন (Asynchronous) — পাঠানো ও পাওয়ার মধ্যে সময়ের ব্যবধান থাকে। ভিডিও কল সমকালীন (Synchronous)।" },
  { q: "বিশ্বগ্রামের ফলে কোন সুবিধাটি সবচেয়ে উল্লেখযোগ্য?", options: ["দূরত্ব কমে যাওয়া","আবহাওয়া পরিবর্তন","বিশ্বব্যাপী তাৎক্ষণিক যোগাযোগ","জনসংখ্যা হ্রাস"], answer: 2, explanation: "বিশ্বগ্রামের সবচেয়ে বড় সুবিধা হলো বিশ্বব্যাপী তাৎক্ষণিক যোগাযোগ। ইন্টারনেটের মাধ্যমে মুহূর্তেই যোগাযোগ সম্ভব।" },
  { q: "Social Media কোন ধরনের যোগাযোগ মাধ্যম?", options: ["Interactive (দ্বিমুখী)","Broadcast (একমুখী)","শুধু পাঠানোর মাধ্যম","কোনোটাই নয়"], answer: 0, explanation: "Social Media Interactive (দ্বিমুখী) মাধ্যম — ব্যবহারকারী পাঠাতে ও পেতে উভয়ই পারেন, মন্তব্য ও প্রতিক্রিয়া জানাতে পারেন।" },
  { q: "বিশ্বগ্রামের নেতিবাচক প্রভাব কোনটি?", options: ["জ্ঞান বৃদ্ধি","যোগাযোগ সহজ হওয়া","কর্মসংস্থান বৃদ্ধি","সাংস্কৃতিক আগ্রাসন ও গোপনীয়তা লঙ্ঘন"], answer: 3, explanation: "বিশ্বগ্রামের নেতিবাচক প্রভাব: সাংস্কৃতিক আগ্রাসন, গোপনীয়তা লঙ্ঘন, সাইবার অপরাধ বৃদ্ধি।" },
  { q: "Video Conferencing কোন ধরনের যোগাযোগ?", options: ["অসমকালীন একমুখী","সমকালীন (Synchronous) দ্বিমুখী","শুধু অডিও","শুধু ভিডিও"], answer: 1, explanation: "Video Conferencing সমকালীন (Synchronous) দ্বিমুখী যোগাযোগ — একই সময়ে দেখা ও কথা বলা যায়। Zoom, Google Meet এর উদাহরণ।" },
  { q: "ICT-র পূর্ণরূপ কী?", options: ["Information and Communication Technology","International Computer Technology","Integrated Communication Terminal","Information Control Technology"], answer: 0, explanation: "ICT = Information and Communication Technology। তথ্য সংগ্রহ, প্রক্রিয়াকরণ, সংরক্ষণ ও বিতরণের জন্য ব্যবহৃত প্রযুক্তির সমষ্টি।" },
  { q: "বিশ্বগ্রাম ধারণার কেন্দ্রীয় বিষয় কী?", options: ["পৃথিবী সত্যিই ছোট হয়ে গেছে","সব দেশ একসাথে মিলে গেছে","ভ্রমণ সহজ হয়েছে","ICT ব্যবহারে পৃথিবী ছোট গ্রামের মতো একটি সম্প্রদায়"], answer: 3, explanation: "বিশ্বগ্রামের কেন্দ্রীয় বিষয়: ICT ব্যবহারে পৃথিবীর মানুষ একে অপরের নিকটবর্তী হয়েছে — একটি সম্প্রদায়ের মতো।" },
];
export default function GlobalVillageQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#0284c7";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — বিশ্বগ্রাম</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f0f9ff",border:"1px solid #bae6fd",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
