"use client";
import { useState } from "react";
const questions = [
  { q: "প্রোগ্রামিং ভাষার প্রথম প্রজন্ম (1GL) কোনটি?", options: ["মেশিন ভাষা","অ্যাসেম্বলি ভাষা","C ভাষা","Python"], answer: 0, explanation: "1GL = Machine Language। সরাসরি 0 ও 1 (বাইনারি) দিয়ে লেখা হয়। CPU সরাসরি বোঝে, কোনো ট্রান্সলেটর দরকার নেই।" },
  { q: "অ্যাসেম্বলি ভাষাকে মেশিন ভাষায় রূপান্তর করে কে?", options: ["Compiler","Interpreter","Assembler","Linker"], answer: 2, explanation: "Assembler হলো সেই প্রোগ্রাম যা Assembly Language (mnemonics) কে Machine Language-এ রূপান্তর করে।" },
  { q: "কম্পাইলার ও ইন্টারপ্রেটারের মধ্যে মূল পার্থক্য কী?", options: ["ইন্টারপ্রেটার দ্রুততর","কম্পাইলার পুরো প্রোগ্রাম একসাথে অনুবাদ করে, ইন্টারপ্রেটার লাইন ধরে ধরে","কম্পাইলার শুধু C-তে ব্যবহার হয়","কোনো পার্থক্য নেই"], answer: 1, explanation: "Compiler: পুরো সোর্স কোড একবারে অনুবাদ করে Object file তৈরি করে। Interpreter: প্রতিটি লাইন পড়ে তাৎক্ষণিকভাবে কার্যকর করে।" },
  { q: "উচ্চস্তরের প্রোগ্রামিং ভাষার উদাহরণ কোনটি?", options: ["ADD, MOV, SUB","0101, 1010","BIOS, DOS","C, Python, Java"], answer: 3, explanation: "C, Python, Java হলো High-Level Language — মানুষের ভাষার কাছাকাছি। Machine ও Assembly Language নিম্নস্তরের।" },
  { q: "Source Code কী?", options: ["CPU-র বোধগম্য বাইনারি কোড","Compiler-এর আউটপুট","প্রোগ্রামারের লেখা মানব-পাঠযোগ্য কোড","Runtime-এ তৈরি কোড"], answer: 2, explanation: "Source Code হলো প্রোগ্রামার যে কোড লেখেন (C, Python ইত্যাদিতে)। এটি মানব-পাঠযোগ্য। Compiler/Interpreter এটিকে Machine Code-এ রূপান্তর করে।" },
  { q: "Object Code কী?", options: ["Compiler-এর তৈরি মধ্যবর্তী মেশিন কোড","প্রোগ্রামারের লেখা কোড","Assembly Language কোড","Error বার্তা"], answer: 0, explanation: "Object Code হলো Compiler-এর তৈরি মধ্যবর্তী বাইনারি ফাইল। Linker এই Object Code-কে Executable File-এ পরিণত করে।" },
  { q: "অ্যাসেম্বলি ভাষায় কী ধরনের চিহ্ন ব্যবহার হয়?", options: ["শুধু 0 ও 1","বাংলা শব্দ","গাণিতিক সূত্র","Mnemonics (ADD, MOV, SUB)"], answer: 3, explanation: "Assembly Language-এ Mnemonic কোড ব্যবহার হয়: ADD (যোগ), SUB (বিয়োগ), MOV (মান সরানো)। এগুলো মেশিন কোডের চেয়ে পড়তে সহজ।" },
  { q: "কোন ভাষা সরাসরি কম্পিউটারের হার্ডওয়্যার নিয়ন্ত্রণ করতে পারে?", options: ["শুধু C ভাষা","মেশিন ভাষা ও অ্যাসেম্বলি ভাষা","শুধু Java","শুধু Python"], answer: 1, explanation: "Machine Language ও Assembly Language (নিম্নস্তরের ভাষা) সরাসরি হার্ডওয়্যার নিয়ন্ত্রণ করতে পারে। High-Level Language পারে না।" },
  { q: "5GL (পঞ্চম প্রজন্মের ভাষা) কোন ধরনের কাজে ব্যবহৃত হয়?", options: ["কৃত্রিম বুদ্ধিমত্তা ও বিশেষজ্ঞ সিস্টেম","গেম ডিজাইন","ওয়েব ডিজাইন","ডেটাবেজ"], answer: 0, explanation: "5GL মূলত AI ও Expert System-এ ব্যবহৃত হয়। Prolog এর উদাহরণ। ব্যবহারকারী সমস্যা বর্ণনা করেন, ভাষাই সমাধান খোঁজে।" },
  { q: "ইন্টারপ্রেটার ব্যবহারের সুবিধা কী?", options: ["প্রোগ্রাম দ্রুত চলে","Object file তৈরি হয়","কম মেমোরি লাগে","ত্রুটি (error) তাৎক্ষণিকভাবে ধরা যায়"], answer: 3, explanation: "Interpreter লাইন ধরে ধরে চালায়, তাই প্রতিটি লাইনের error তাৎক্ষণিক ধরা পড়ে — ডিবাগিং সহজ হয়।" },
];
export default function ProgrammingConceptsQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#7c3aed";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — প্রোগ্রামিং ভাষার ধারণা</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f5f3ff",border:"1px solid #ddd6fe",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
