"use client";
import { useState } from "react";
const questions = [
  { q: "Artificial Intelligence (AI) কী?", options: ["মানুষের মতো চিন্তা ও সিদ্ধান্ত নেওয়ার ক্ষমতাসম্পন্ন যন্ত্র","শুধু রোবট","ইন্টারনেট প্রযুক্তি","একটি প্রোগ্রামিং ভাষা"], answer: 0, explanation: "AI হলো মানুষের বুদ্ধিমত্তার অনুকরণে যন্ত্রে কৃত্রিম বুদ্ধিমত্তা তৈরির বিজ্ঞান। এটি শিখতে, যুক্তি দিতে ও সমস্যা সমাধান করতে পারে।" },
  { q: "Nanotechnology-তে 1 nm (ন্যানোমিটার) = কত মিটার?", options: ["10⁻⁶ মিটার","10⁻³ মিটার","10⁻⁹ মিটার","10⁻¹² মিটার"], answer: 2, explanation: "1 nm (nanometer) = 10⁻⁹ meter। Nanotechnology ন্যানোমিটার স্কেলে পদার্থ নিয়ন্ত্রণ করে — চুলের চেয়ে ৮০,০০০ গুণ পাতলা।" },
  { q: "Cryosurgery-তে কোন পদ্ধতি ব্যবহার হয়?", options: ["লেজার রশ্মি","তীব্র শীতল তাপমাত্রায় রোগাক্রান্ত টিস্যু ধ্বংস","বিদ্যুৎ প্রবাহ","রাসায়নিক দ্রব্য"], answer: 1, explanation: "Cryosurgery তীব্র শীতল তাপমাত্রা (তরল নাইট্রোজেন -196°C বা Argon গ্যাস) ব্যবহার করে ক্যান্সার কোষসহ রোগাক্রান্ত টিস্যু ধ্বংস করে।" },
  { q: "Bioinformatics কোন দুটি ক্ষেত্রের সমন্বয়?", options: ["রসায়ন + পদার্থবিজ্ঞান","চিকিৎসা + প্রকৌশল","গণিত + পরিসংখ্যান","জীববিজ্ঞান + তথ্য প্রযুক্তি"], answer: 3, explanation: "Bioinformatics = Biology + Information Technology। DNA সিকোয়েন্স বিশ্লেষণ, প্রোটিন গঠন নির্ধারণ, জিনোম ম্যাপিংয়ে ব্যবহৃত হয়।" },
  { q: "Virtual Reality (VR)-এ কী হয়?", options: ["সত্যিকারের ভ্রমণ","টেলিভিশনের উন্নত সংস্করণ","কৃত্রিম পরিবেশে বাস্তবের অনুভূতি তৈরি হয়","ইন্টারনেট ব্রাউজিং"], answer: 2, explanation: "Virtual Reality কম্পিউটার প্রযুক্তিতে তৈরি কৃত্রিম পরিবেশ যেখানে ব্যবহারকারী VR Headset পরে বাস্তবের মতো অনুভব করে।" },
  { q: "Genetic Engineering-এ কী করা হয়?", options: ["জীবের DNA পরিবর্তন বা পুনর্বিন্যাস করা","রোবট তৈরি করা","AI প্রোগ্রামিং","ন্যানো পার্টিকেল তৈরি"], answer: 0, explanation: "Genetic Engineering জীবের DNA কে পরিবর্তন বা পুনর্বিন্যাস করে নতুন বৈশিষ্ট্য তৈরি করে। GMO ফসল, ইনসুলিন উৎপাদনে ব্যবহৃত।" },
  { q: "Augmented Reality (AR) কী?", options: ["সম্পূর্ণ কৃত্রিম পরিবেশ","শুধু ভিডিও গেম","ইন্টারনেট প্রযুক্তি","বাস্তব পরিবেশে কৃত্রিম তথ্য/বস্তু যোগ করা"], answer: 3, explanation: "AR বাস্তব পরিবেশের উপর কৃত্রিম তথ্য/বস্তু আরোপিত করে। Pokemon Go, Google Maps AR এর উদাহরণ। VR-এর সাথে পার্থক্য: AR বাস্তবের সাথে মিশ্রিত।" },
  { q: "Robotics-এর প্রধান ব্যবহার ক্ষেত্র কোনটি?", options: ["শুধু খেলনা তৈরি","শিল্প, চিকিৎসা ও বিপজ্জনক কাজ","শুধু কৃষি","শুধু মহাকাশ"], answer: 1, explanation: "Robotics ব্যবহার হয়: শিল্প কারখানায় (স্বয়ংক্রিয় উৎপাদন), চিকিৎসায় (Surgery Robot), বিপজ্জনক কাজে (বোমা নিষ্ক্রিয়করণ), মহাকাশ গবেষণায়।" },
  { q: "Nanotechnology কোন ক্ষেত্রে ব্যবহৃত হয়?", options: ["চিকিৎসা, ইলেকট্রনিক্স, পরিবেশ ও উপকরণ বিজ্ঞান","শুধু চিকিৎসায়","শুধু ইলেকট্রনিক্সে","শুধু প্রতিরক্ষায়"], answer: 0, explanation: "Nanotechnology বহুক্ষেত্রে ব্যবহৃত: ক্যান্সার চিকিৎসায় nano drug delivery, ক্ষুদ্র ইলেকট্রনিক চিপ, সৌরকোষ দক্ষতা বৃদ্ধি, উন্নত উপকরণ।" },
  { q: "Machine Learning কোন বিষয়ের অংশ?", options: ["Robotics","Virtual Reality","Nanotechnology","Artificial Intelligence (AI)"], answer: 3, explanation: "Machine Learning হলো AI-এর একটি শাখা — কম্পিউটার অভিজ্ঞতা থেকে নিজে নিজে শেখে, প্রোগ্রামিং ছাড়াই নতুন পরিস্থিতিতে মানিয়ে নেয়।" },
];
export default function RecentTrendsQuiz() {
  const [phase,setPhase]=useState<"idle"|"quiz"|"result">("idle");
  const [cur,setCur]=useState(0);const [sel,setSel]=useState<number|null>(null);
  const [ans,setAns]=useState<(number|null)[]>(Array(10).fill(null));
  const score=ans.filter((a,i)=>a===questions[i].answer).length;
  function start(){setAns(Array(10).fill(null));setCur(0);setSel(null);setPhase("quiz");}
  function pick(i:number){if(sel!==null)return;setSel(i);const u=[...ans];u[cur]=i;setAns(u);}
  function next(){if(cur===9)setPhase("result");else{setCur(c=>c+1);setSel(null);}}
  const q=questions[cur],ok=sel===q?.answer;
  const grade=score>=9?"A+":score>=8?"A":score>=7?"A-":score>=5?"B":score>=3?"C":"F";
  const gc=score>=7?"#16a34a":score>=5?"#d97706":"#dc2626";
  const C="#7c3aed";
  if(phase==="idle") return <div style={{textAlign:"center",padding:"2rem 0"}}><p style={{color:"#6b7280",marginBottom:"1.5rem"}}>১০টি MCQ — সাম্প্রতিক প্রবণতা</p><button onClick={start} style={S(C)}>কুইজ শুরু করুন →</button></div>;
  if(phase==="result") return(<div style={{textAlign:"center",padding:"2rem 0"}}><div style={{fontSize:"4rem",marginBottom:"0.5rem"}}>{score>=7?"🎉":score>=5?"👍":"📚"}</div><div style={{fontSize:"3rem",fontWeight:800,color:gc}}>{grade}</div><div style={{fontSize:"1.5rem",fontWeight:700,margin:"0.5rem 0"}}>{score} / ১০ সঠিক</div><div style={{textAlign:"left",margin:"1.5rem 0"}}>{questions.map((qq,i)=>{const o=ans[i]===qq.answer;return(<div key={i} style={{display:"flex",gap:"0.75rem",padding:"0.75rem",borderRadius:"0.5rem",marginBottom:"0.5rem",background:o?"#f0fdf4":"#fef2f2",border:`1px solid ${o?"#bbf7d0":"#fecaca"}`}}><span>{o?"✅":"❌"}</span><div><div style={{fontSize:"0.875rem",fontWeight:600,color:"#1f2937"}}>{i+1}. {qq.q}</div>{!o&&<div style={{fontSize:"0.8rem",color:"#16a34a",marginTop:"0.25rem"}}>সঠিক: {qq.options[qq.answer]}</div>}</div></div>);})}</div><button onClick={start} style={S(C)}>আবার চেষ্টা করুন</button></div>);
  return(<div><div style={{height:"6px",background:"#e5e7eb",borderRadius:"99px",marginBottom:"1.5rem"}}><div style={{height:"100%",width:`${((cur+1)/10)*100}%`,background:C,borderRadius:"99px",transition:"width 0.3s"}}/></div><div style={{background:"#f5f3ff",border:"1px solid #ddd6fe",borderRadius:"0.75rem",padding:"1.25rem",marginBottom:"1.25rem",fontWeight:600,fontSize:"1.05rem",color:"#0f172a",lineHeight:1.6}}>{cur+1}. {q.q}</div><div style={{display:"flex",flexDirection:"column",gap:"0.625rem",marginBottom:"1.25rem"}}>{q.options.map((opt,i)=>{let bg="#fff",border="#d1d5db",color="#374151";if(sel!==null){if(i===q.answer){bg="#f0fdf4";border="#86efac";color="#15803d";}else if(i===sel&&i!==q.answer){bg="#fef2f2";border="#fca5a5";color="#b91c1c";}else{bg="#f9fafb";color="#9ca3af";}}return <button key={i} onClick={()=>pick(i)} disabled={sel!==null} style={{display:"flex",alignItems:"center",gap:"0.75rem",padding:"0.875rem 1rem",borderRadius:"0.625rem",border:`2px solid ${border}`,background:bg,color,textAlign:"left",cursor:sel!==null?"default":"pointer",fontSize:"0.95rem",fontWeight:500}}><span style={{display:"inline-flex",alignItems:"center",justifyContent:"center",width:"1.75rem",height:"1.75rem",borderRadius:"50%",background:i===q.answer&&sel!==null?"#16a34a":sel===i&&i!==q.answer?"#dc2626":"#e5e7eb",color:sel!==null&&(i===q.answer||i===sel)?"#fff":"#374151",fontSize:"0.8rem",fontWeight:700,flexShrink:0}}>{["ক","খ","গ","ঘ"][i]}</span>{opt}</button>;})} </div>{sel!==null&&<div style={{padding:"1rem",borderRadius:"0.625rem",background:ok?"#f0fdf4":"#fef9c3",border:`1px solid ${ok?"#86efac":"#fde68a"}`,marginBottom:"1.25rem",fontSize:"0.9rem",color:"#1e293b"}}><strong>{ok?"✅ সঠিক!":"❌ ভুল।"}</strong> {q.explanation}</div>}{sel!==null&&<button onClick={next} style={S(C)}>{cur===9?"ফলাফল দেখুন →":"পরের প্রশ্ন →"}</button>}</div>);
}
function S(bg:string):React.CSSProperties{return{background:bg,color:"#fff",border:"none",borderRadius:"0.625rem",padding:"0.75rem 1.75rem",fontSize:"1rem",fontWeight:600,cursor:"pointer"};}
